/**
 * Lists product photos whose background is opaque (no transparent corners).
 * On saturated aisle colors those photos show as boxes, so colored panels
 * prefer transparent pack shots. Re-run after catalog image changes:
 *
 *   pnpm images:opaque
 */
import { readFile, writeFile } from "node:fs/promises";
import sharp from "sharp";
import { categories } from "../src/data/products";
import { isMissingProductImage } from "../src/lib/productImage";

const OUTPUT = "src/data/opaque-pack-shots.generated.ts";

async function load(src: string): Promise<Buffer> {
  if (/^https?:\/\//.test(src)) {
    const response = await fetch(src);
    if (!response.ok) throw new Error(`${response.status} for ${src}`);
    return Buffer.from(await response.arrayBuffer());
  }
  return readFile(`public${decodeURI(src)}`);
}

async function isOpaque(src: string): Promise<boolean> {
  const { data, info } = await sharp(await load(src))
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const alpha = (x: number, y: number) => data[(y * info.width + x) * 4 + 3];
  const corners = [
    alpha(0, 0),
    alpha(info.width - 1, 0),
    alpha(0, info.height - 1),
    alpha(info.width - 1, info.height - 1),
  ];
  return corners.some((value) => value >= 20);
}

const images = [
  ...new Set(
    categories
      .flatMap((category) => category.products.map((product) => product.image))
      .filter((image) => !isMissingProductImage(image)),
  ),
];
const opaque: string[] = [];
for (const image of images) {
  try {
    if (await isOpaque(image)) opaque.push(image);
  } catch (error) {
    console.warn(`Skipped ${image}: ${String(error)}`);
  }
}
opaque.sort();
await writeFile(
  OUTPUT,
  `// Generated by scripts/find-opaque-pack-shots.ts. Do not edit by hand.\n` +
    `// Product photos with opaque backgrounds; colored panels prefer others.\n` +
    `export const opaquePackShots: ReadonlySet<string> = new Set(${JSON.stringify(opaque, null, 2)});\n`,
);
console.log(`Checked ${images.length} images; ${opaque.length} opaque → ${OUTPUT}`);
