import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { categories } from "../src/data/products";

const root = process.cwd();
const outputDirectory = path.join(root, "public/assets/optimized");
const manifestPath = path.join(root, "src/data/optimized-images.ts");
const rasterImage = /\.(?:png|jpe?g|webp|avif)$/i;
const references = new Set<string>();
const heroImages = new Set(categories.map((category) => category.heroImage));

// Keep variants for hidden code-managed catalog entries too, so a later release
// cannot accidentally put an original multi-megabyte pack shot back on the page.
async function collectReferences(directory: string): Promise<void> {
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    const filename = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      await collectReferences(filename);
    } else if (/\.tsx?$/.test(entry.name) && !/\.test\.tsx?$/.test(entry.name) && entry.name !== "optimized-images.ts") {
      const source = await readFile(filename, "utf8");
      for (const match of source.matchAll(/["'](\/assets\/[^"'\n]+\.(?:png|jpe?g|webp|avif))["']/gi)) {
        references.add(match[1]);
      }
    }
  }
}

await collectReferences(path.join(root, "src"));
await mkdir(outputDirectory, { recursive: true });
sharp.concurrency(2);

const manifest: Record<string, { src: string; srcSet: string }> = {};
let originalBytes = 0;
let fullSizeBytes = 0;
let smallestBytes = 0;

for (const source of [...references].sort()) {
  if (!rasterImage.test(source)) continue;
  const filename = path.join(root, "public", source.slice(1));
  const input = await readFile(filename);
  const metadata = await sharp(input).metadata().catch((error: unknown) => {
    throw new Error(`Cannot decode ${source}: ${String(error)}`);
  });
  if (!metadata.width) throw new Error(`Missing image width: ${source}`);

  const requestedMaxWidth = Math.min(metadata.width, heroImages.has(source) ? 1920 : 1280);
  // Decode the often enormous source once. Encode every smaller candidate from
  // this bounded raster instead of decoding the original again for each size.
  const master = await sharp(input)
    .rotate()
    .resize({ width: requestedMaxWidth, withoutEnlargement: true })
    .raw()
    .toBuffer({ resolveWithObject: true });
  const maxWidth = master.info.width;
  const widths = [...new Set([160, 320, 640, 1280, maxWidth])]
    .filter((width) => width <= maxWidth)
    .sort((left, right) => left - right);
  const hash = createHash("sha256").update(input).update("webp-v2-quality82-master").digest("hex").slice(0, 12);
  const basename = path.basename(source, path.extname(source))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
  const variants: Array<{ src: string; width: number; bytes: number }> = [];

  for (const width of widths) {
    const outputName = `${basename}-${hash}-${width}.webp`;
    const outputPath = path.join(outputDirectory, outputName);
    let bytes: number;
    try {
      bytes = (await stat(outputPath)).size;
    } catch {
      const result = await sharp(master.data, { raw: master.info })
        .resize({ width, withoutEnlargement: true })
        .webp({ quality: 82, alphaQuality: 100, effort: 4 })
        .toFile(outputPath);
      bytes = result.size;
    }
    variants.push({ src: `/assets/optimized/${outputName}`, width, bytes });
  }

  const largest = variants[variants.length - 1];
  manifest[source] = {
    src: largest.src,
    srcSet: variants.map((variant) => `${variant.src} ${variant.width}w`).join(", "),
  };
  originalBytes += input.length;
  fullSizeBytes += largest.bytes;
  smallestBytes += variants[0].bytes;
}

await writeFile(manifestPath, `// Generated by scripts/optimize-images.ts. Do not edit by hand.
export interface OptimizedImage {
  src: string;
  srcSet: string;
}

export const optimizedImages: Record<string, OptimizedImage> = ${JSON.stringify(manifest, null, 2)};
`);

const megabytes = (bytes: number) => (bytes / 1_000_000).toFixed(2);
console.log(`Optimized ${Object.keys(manifest).length} bundled photos: ${megabytes(originalBytes)} MB originals → ${megabytes(fullSizeBytes)} MB largest variants; ${megabytes(smallestBytes)} MB thumbnail variants.`);
