// Generated by scripts/find-opaque-pack-shots.ts. Do not edit by hand.
// Product photos with opaque backgrounds; colored panels prefer others.
export const opaquePackShots: ReadonlySet<string> = new Set([
  "https://kayco-planning-dashboard.pages.dev/product-images/0692a82189a83ad76bae5600.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/06aba510ec38f79828ebe2e0.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/1893f3eb6076e83480cc2b3a.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/1efacc168ac0184f608d037e.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/225f3371fa11aadde5867295.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/24872ec6e3c162233923d219.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/31ec7e4bdde40e80731be003.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/4767d5cf0de780132b5b05bc.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/557b07d1fb9a863c839dec05.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/5a614e6832c802c89fae7fca.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/714472e806cb5d42817d3f58.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/768b105c9062de3e8b924ab2.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/8396974aa8aca6cdc90ac430.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/861686799fe3f8307e71e7fa.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/9084cef153b5612277e65be8.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/98ad7af3eac79746bd1ba3a7.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/98b258e7e28f570af9009bd6.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/a4f53bfb42c10b160f79c5ed.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/ab0c53552f6176ffa6afbea2.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/bde9d0bc485e6098f10ba5a9.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/be2bfcff49576348eea0d9d0.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/be848c12b3737c1f3176469c.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/c9c28c0c672e19bc49fa8fd8.webp",
  "https://kayco-planning-dashboard.pages.dev/product-images/d356b61522e6c4fe3e83fd69.webp"
]);
