// Generated by scripts/optimize-images.ts. Do not edit by hand.
export interface OptimizedImage {
  src: string;
  srcSet: string;
}

export const optimizedImages: Record<string, OptimizedImage> = {
  "/assets/Beverage/730365.png": {
    "src": "/assets/optimized/730365-f4b90132acf5-773.webp",
    "srcSet": "/assets/optimized/730365-f4b90132acf5-160.webp 160w, /assets/optimized/730365-f4b90132acf5-320.webp 320w, /assets/optimized/730365-f4b90132acf5-640.webp 640w, /assets/optimized/730365-f4b90132acf5-773.webp 773w"
  },
  "/assets/Beverage/730366.png": {
    "src": "/assets/optimized/730366-e427414b3d3a-773.webp",
    "srcSet": "/assets/optimized/730366-e427414b3d3a-160.webp 160w, /assets/optimized/730366-e427414b3d3a-320.webp 320w, /assets/optimized/730366-e427414b3d3a-640.webp 640w, /assets/optimized/730366-e427414b3d3a-773.webp 773w"
  },
  "/assets/Beverage/730367-2.png": {
    "src": "/assets/optimized/730367-2-8274b790a560-773.webp",
    "srcSet": "/assets/optimized/730367-2-8274b790a560-160.webp 160w, /assets/optimized/730367-2-8274b790a560-320.webp 320w, /assets/optimized/730367-2-8274b790a560-640.webp 640w, /assets/optimized/730367-2-8274b790a560-773.webp 773w"
  },
  "/assets/Beverage/730380.png": {
    "src": "/assets/optimized/730380-ad7583929632-1057.webp",
    "srcSet": "/assets/optimized/730380-ad7583929632-160.webp 160w, /assets/optimized/730380-ad7583929632-320.webp 320w, /assets/optimized/730380-ad7583929632-640.webp 640w, /assets/optimized/730380-ad7583929632-1057.webp 1057w"
  },
  "/assets/Beverage/730473.png": {
    "src": "/assets/optimized/730473-0d830d75e06c-237.webp",
    "srcSet": "/assets/optimized/730473-0d830d75e06c-160.webp 160w, /assets/optimized/730473-0d830d75e06c-237.webp 237w"
  },
  "/assets/Beverage/730474.png": {
    "src": "/assets/optimized/730474-1b9448e8b5a2-238.webp",
    "srcSet": "/assets/optimized/730474-1b9448e8b5a2-160.webp 160w, /assets/optimized/730474-1b9448e8b5a2-238.webp 238w"
  },
  "/assets/Beverage/730475.png": {
    "src": "/assets/optimized/730475-adf5d72028e6-236.webp",
    "srcSet": "/assets/optimized/730475-adf5d72028e6-160.webp 160w, /assets/optimized/730475-adf5d72028e6-236.webp 236w"
  },
  "/assets/Beverage/Mineral-Water-Still-1L-730395.png": {
    "src": "/assets/optimized/mineral-water-still-1l-730395-81ab81bd9c7e-614.webp",
    "srcSet": "/assets/optimized/mineral-water-still-1l-730395-81ab81bd9c7e-160.webp 160w, /assets/optimized/mineral-water-still-1l-730395-81ab81bd9c7e-320.webp 320w, /assets/optimized/mineral-water-still-1l-730395-81ab81bd9c7e-614.webp 614w"
  },
  "/assets/Beverage/Moscato Juice/Mockups/71006931470.jpg": {
    "src": "/assets/optimized/71006931470-7ac6fc076b34-1280.webp",
    "srcSet": "/assets/optimized/71006931470-7ac6fc076b34-160.webp 160w, /assets/optimized/71006931470-7ac6fc076b34-320.webp 320w, /assets/optimized/71006931470-7ac6fc076b34-640.webp 640w, /assets/optimized/71006931470-7ac6fc076b34-1280.webp 1280w"
  },
  "/assets/Beverage/Moscato Juice/Mockups/71006931471.jpg": {
    "src": "/assets/optimized/71006931471-e5c057169e91-1280.webp",
    "srcSet": "/assets/optimized/71006931471-e5c057169e91-160.webp 160w, /assets/optimized/71006931471-e5c057169e91-320.webp 320w, /assets/optimized/71006931471-e5c057169e91-640.webp 640w, /assets/optimized/71006931471-e5c057169e91-1280.webp 1280w"
  },
  "/assets/Beverage/Sparkling Beverage/Cola/Images/730382.png": {
    "src": "/assets/optimized/730382-598e45d12ea4-832.webp",
    "srcSet": "/assets/optimized/730382-598e45d12ea4-160.webp 160w, /assets/optimized/730382-598e45d12ea4-320.webp 320w, /assets/optimized/730382-598e45d12ea4-640.webp 640w, /assets/optimized/730382-598e45d12ea4-832.webp 832w"
  },
  "/assets/Beverage/Sparkling Beverage/Cola/Images/730838.png": {
    "src": "/assets/optimized/730838-1d03ae46cd8b-832.webp",
    "srcSet": "/assets/optimized/730838-1d03ae46cd8b-160.webp 160w, /assets/optimized/730838-1d03ae46cd8b-320.webp 320w, /assets/optimized/730838-1d03ae46cd8b-640.webp 640w, /assets/optimized/730838-1d03ae46cd8b-832.webp 832w"
  },
  "/assets/Beverage/Sparkling Beverage/Tuscanini Flavored Seltzer Water_Mockups/Tuscanini Flavored Seltzer 0.5L 2.jpg": {
    "src": "/assets/optimized/tuscanini-flavored-seltzer-0-5l-2-934654aa4990-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-flavored-seltzer-0-5l-2-934654aa4990-160.webp 160w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-2-934654aa4990-320.webp 320w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-2-934654aa4990-640.webp 640w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-2-934654aa4990-1280.webp 1280w"
  },
  "/assets/Beverage/Sparkling Beverage/Tuscanini Flavored Seltzer Water_Mockups/Tuscanini Flavored Seltzer 0.5L 3.jpg": {
    "src": "/assets/optimized/tuscanini-flavored-seltzer-0-5l-3-7d7a4b27e81a-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-flavored-seltzer-0-5l-3-7d7a4b27e81a-160.webp 160w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-3-7d7a4b27e81a-320.webp 320w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-3-7d7a4b27e81a-640.webp 640w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-3-7d7a4b27e81a-1280.webp 1280w"
  },
  "/assets/Beverage/Sparkling Beverage/Tuscanini Flavored Seltzer Water_Mockups/Tuscanini Flavored Seltzer 0.5L 4.jpg": {
    "src": "/assets/optimized/tuscanini-flavored-seltzer-0-5l-4-17f218e3062f-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-flavored-seltzer-0-5l-4-17f218e3062f-160.webp 160w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-4-17f218e3062f-320.webp 320w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-4-17f218e3062f-640.webp 640w, /assets/optimized/tuscanini-flavored-seltzer-0-5l-4-17f218e3062f-1280.webp 1280w"
  },
  "/assets/Biscotti/730575.png": {
    "src": "/assets/optimized/730575-facd4964d97f-1011.webp",
    "srcSet": "/assets/optimized/730575-facd4964d97f-160.webp 160w, /assets/optimized/730575-facd4964d97f-320.webp 320w, /assets/optimized/730575-facd4964d97f-640.webp 640w, /assets/optimized/730575-facd4964d97f-1011.webp 1011w"
  },
  "/assets/Biscotti/730576.png": {
    "src": "/assets/optimized/730576-e00621d959fa-800.webp",
    "srcSet": "/assets/optimized/730576-e00621d959fa-160.webp 160w, /assets/optimized/730576-e00621d959fa-320.webp 320w, /assets/optimized/730576-e00621d959fa-640.webp 640w, /assets/optimized/730576-e00621d959fa-800.webp 800w"
  },
  "/assets/Biscotti/730577.png": {
    "src": "/assets/optimized/730577-f90621a02819-800.webp",
    "srcSet": "/assets/optimized/730577-f90621a02819-160.webp 160w, /assets/optimized/730577-f90621a02819-320.webp 320w, /assets/optimized/730577-f90621a02819-640.webp 640w, /assets/optimized/730577-f90621a02819-800.webp 800w"
  },
  "/assets/Biscotti/730578.png": {
    "src": "/assets/optimized/730578-1c05eba531e5-800.webp",
    "srcSet": "/assets/optimized/730578-1c05eba531e5-160.webp 160w, /assets/optimized/730578-1c05eba531e5-320.webp 320w, /assets/optimized/730578-1c05eba531e5-640.webp 640w, /assets/optimized/730578-1c05eba531e5-800.webp 800w"
  },
  "/assets/Biscotti/730579.png": {
    "src": "/assets/optimized/730579-2e8b5a5d670e-800.webp",
    "srcSet": "/assets/optimized/730579-2e8b5a5d670e-160.webp 160w, /assets/optimized/730579-2e8b5a5d670e-320.webp 320w, /assets/optimized/730579-2e8b5a5d670e-640.webp 640w, /assets/optimized/730579-2e8b5a5d670e-800.webp 800w"
  },
  "/assets/Chestnuts/730462.png": {
    "src": "/assets/optimized/730462-cb53df3015cb-1280.webp",
    "srcSet": "/assets/optimized/730462-cb53df3015cb-160.webp 160w, /assets/optimized/730462-cb53df3015cb-320.webp 320w, /assets/optimized/730462-cb53df3015cb-640.webp 640w, /assets/optimized/730462-cb53df3015cb-1280.webp 1280w"
  },
  "/assets/Chestnuts/Tuscanini Chestnuts_Original.png": {
    "src": "/assets/optimized/tuscanini-chestnuts-original-6ec25f51c1f9-1123.webp",
    "srcSet": "/assets/optimized/tuscanini-chestnuts-original-6ec25f51c1f9-160.webp 160w, /assets/optimized/tuscanini-chestnuts-original-6ec25f51c1f9-320.webp 320w, /assets/optimized/tuscanini-chestnuts-original-6ec25f51c1f9-640.webp 640w, /assets/optimized/tuscanini-chestnuts-original-6ec25f51c1f9-1123.webp 1123w"
  },
  "/assets/Chestnuts/Tuscanini Chestnuts_Salt & Pepper.png": {
    "src": "/assets/optimized/tuscanini-chestnuts-salt-pepper-9e9f783c6219-1123.webp",
    "srcSet": "/assets/optimized/tuscanini-chestnuts-salt-pepper-9e9f783c6219-160.webp 160w, /assets/optimized/tuscanini-chestnuts-salt-pepper-9e9f783c6219-320.webp 320w, /assets/optimized/tuscanini-chestnuts-salt-pepper-9e9f783c6219-640.webp 640w, /assets/optimized/tuscanini-chestnuts-salt-pepper-9e9f783c6219-1123.webp 1123w"
  },
  "/assets/Chips/IMG_0022-2.jpg": {
    "src": "/assets/optimized/img-0022-2-a18883c29d21-1280.webp",
    "srcSet": "/assets/optimized/img-0022-2-a18883c29d21-160.webp 160w, /assets/optimized/img-0022-2-a18883c29d21-320.webp 320w, /assets/optimized/img-0022-2-a18883c29d21-640.webp 640w, /assets/optimized/img-0022-2-a18883c29d21-1280.webp 1280w"
  },
  "/assets/Chips/IMG_0032.jpg": {
    "src": "/assets/optimized/img-0032-4f6dab63547b-1280.webp",
    "srcSet": "/assets/optimized/img-0032-4f6dab63547b-160.webp 160w, /assets/optimized/img-0032-4f6dab63547b-320.webp 320w, /assets/optimized/img-0032-4f6dab63547b-640.webp 640w, /assets/optimized/img-0032-4f6dab63547b-1280.webp 1280w"
  },
  "/assets/Chips/Tuscanini-Classic-Potato-Chips-1oz-730350.png": {
    "src": "/assets/optimized/tuscanini-classic-potato-chips-1oz-730350-e8ec599a0699-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-classic-potato-chips-1oz-730350-e8ec599a0699-160.webp 160w, /assets/optimized/tuscanini-classic-potato-chips-1oz-730350-e8ec599a0699-320.webp 320w, /assets/optimized/tuscanini-classic-potato-chips-1oz-730350-e8ec599a0699-640.webp 640w, /assets/optimized/tuscanini-classic-potato-chips-1oz-730350-e8ec599a0699-1280.webp 1280w"
  },
  "/assets/Chips/Tuscanini-Potato-Chips-with-Olive-Oil-Classic-4.6oz-730340.png": {
    "src": "/assets/optimized/tuscanini-potato-chips-with-olive-oil-classic-4-6oz-730340-0a1e08cc7325-993.webp",
    "srcSet": "/assets/optimized/tuscanini-potato-chips-with-olive-oil-classic-4-6oz-730340-0a1e08cc7325-160.webp 160w, /assets/optimized/tuscanini-potato-chips-with-olive-oil-classic-4-6oz-730340-0a1e08cc7325-320.webp 320w, /assets/optimized/tuscanini-potato-chips-with-olive-oil-classic-4-6oz-730340-0a1e08cc7325-640.webp 640w, /assets/optimized/tuscanini-potato-chips-with-olive-oil-classic-4-6oz-730340-0a1e08cc7325-993.webp 993w"
  },
  "/assets/Chips/Tuscanini-Potato-Chips-with-Olive-Oil-Rippled-4.6oz-730342-web.png": {
    "src": "/assets/optimized/tuscanini-potato-chips-with-olive-oil-rippled-4-6oz-730342-w-6fc9878be7b2-323.webp",
    "srcSet": "/assets/optimized/tuscanini-potato-chips-with-olive-oil-rippled-4-6oz-730342-w-6fc9878be7b2-160.webp 160w, /assets/optimized/tuscanini-potato-chips-with-olive-oil-rippled-4-6oz-730342-w-6fc9878be7b2-320.webp 320w, /assets/optimized/tuscanini-potato-chips-with-olive-oil-rippled-4-6oz-730342-w-6fc9878be7b2-323.webp 323w"
  },
  "/assets/Chips/Tuscanini-Potato-Chips-with-Olive-Oil-Rosemary-4.6oz-730341.png": {
    "src": "/assets/optimized/tuscanini-potato-chips-with-olive-oil-rosemary-4-6oz-730341-5dd2459fe4b3-1016.webp",
    "srcSet": "/assets/optimized/tuscanini-potato-chips-with-olive-oil-rosemary-4-6oz-730341-5dd2459fe4b3-160.webp 160w, /assets/optimized/tuscanini-potato-chips-with-olive-oil-rosemary-4-6oz-730341-5dd2459fe4b3-320.webp 320w, /assets/optimized/tuscanini-potato-chips-with-olive-oil-rosemary-4-6oz-730341-5dd2459fe4b3-640.webp 640w, /assets/optimized/tuscanini-potato-chips-with-olive-oil-rosemary-4-6oz-730341-5dd2459fe4b3-1016.webp 1016w"
  },
  "/assets/Chips/Tuscanini-Rippled-Potato-Chips-1oz-730351.png": {
    "src": "/assets/optimized/tuscanini-rippled-potato-chips-1oz-730351-3e7bcfdd6d20-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-rippled-potato-chips-1oz-730351-3e7bcfdd6d20-160.webp 160w, /assets/optimized/tuscanini-rippled-potato-chips-1oz-730351-3e7bcfdd6d20-320.webp 320w, /assets/optimized/tuscanini-rippled-potato-chips-1oz-730351-3e7bcfdd6d20-640.webp 640w, /assets/optimized/tuscanini-rippled-potato-chips-1oz-730351-3e7bcfdd6d20-1280.webp 1280w"
  },
  "/assets/Chocolate Bars/pisa large 3 LARGER OPTION Topaz Gigapixel 2x scale copy.jpg": {
    "src": "/assets/optimized/pisa-large-3-larger-option-topaz-gigapixel-2x-scale-copy-a405b4a4fa93-1920.webp",
    "srcSet": "/assets/optimized/pisa-large-3-larger-option-topaz-gigapixel-2x-scale-copy-a405b4a4fa93-160.webp 160w, /assets/optimized/pisa-large-3-larger-option-topaz-gigapixel-2x-scale-copy-a405b4a4fa93-320.webp 320w, /assets/optimized/pisa-large-3-larger-option-topaz-gigapixel-2x-scale-copy-a405b4a4fa93-640.webp 640w, /assets/optimized/pisa-large-3-larger-option-topaz-gigapixel-2x-scale-copy-a405b4a4fa93-1280.webp 1280w, /assets/optimized/pisa-large-3-larger-option-topaz-gigapixel-2x-scale-copy-a405b4a4fa93-1920.webp 1920w"
  },
  "/assets/Chocolate Truffle/Info/Pistachio/image001.png": {
    "src": "/assets/optimized/image001-5bf61e03710b-378.webp",
    "srcSet": "/assets/optimized/image001-5bf61e03710b-160.webp 160w, /assets/optimized/image001-5bf61e03710b-320.webp 320w, /assets/optimized/image001-5bf61e03710b-378.webp 378w"
  },
  "/assets/Chocolate Truffles/730480.png": {
    "src": "/assets/optimized/730480-0eb73eebea53-460.webp",
    "srcSet": "/assets/optimized/730480-0eb73eebea53-160.webp 160w, /assets/optimized/730480-0eb73eebea53-320.webp 320w, /assets/optimized/730480-0eb73eebea53-460.webp 460w"
  },
  "/assets/Chocolate Truffles/730481.png": {
    "src": "/assets/optimized/730481-65ba6d5dc2c6-464.webp",
    "srcSet": "/assets/optimized/730481-65ba6d5dc2c6-160.webp 160w, /assets/optimized/730481-65ba6d5dc2c6-320.webp 320w, /assets/optimized/730481-65ba6d5dc2c6-464.webp 464w"
  },
  "/assets/Chocolate Truffles/730482.png": {
    "src": "/assets/optimized/730482-d4e37fcfe6ab-458.webp",
    "srcSet": "/assets/optimized/730482-d4e37fcfe6ab-160.webp 160w, /assets/optimized/730482-d4e37fcfe6ab-320.webp 320w, /assets/optimized/730482-d4e37fcfe6ab-458.webp 458w"
  },
  "/assets/Chocolate Truffles/730484.png": {
    "src": "/assets/optimized/730484-ebc79342b5ef-367.webp",
    "srcSet": "/assets/optimized/730484-ebc79342b5ef-160.webp 160w, /assets/optimized/730484-ebc79342b5ef-320.webp 320w, /assets/optimized/730484-ebc79342b5ef-367.webp 367w"
  },
  "/assets/Chocolate Truffles/730486.png": {
    "src": "/assets/optimized/730486-6b8a238423a8-409.webp",
    "srcSet": "/assets/optimized/730486-6b8a238423a8-160.webp 160w, /assets/optimized/730486-6b8a238423a8-320.webp 320w, /assets/optimized/730486-6b8a238423a8-409.webp 409w"
  },
  "/assets/Chocolate/730598.png": {
    "src": "/assets/optimized/730598-5abb754d1e2c-416.webp",
    "srcSet": "/assets/optimized/730598-5abb754d1e2c-160.webp 160w, /assets/optimized/730598-5abb754d1e2c-320.webp 320w, /assets/optimized/730598-5abb754d1e2c-416.webp 416w"
  },
  "/assets/Crackers/730330.png": {
    "src": "/assets/optimized/730330-a64c6a1182d8-1280.webp",
    "srcSet": "/assets/optimized/730330-a64c6a1182d8-160.webp 160w, /assets/optimized/730330-a64c6a1182d8-320.webp 320w, /assets/optimized/730330-a64c6a1182d8-640.webp 640w, /assets/optimized/730330-a64c6a1182d8-1280.webp 1280w"
  },
  "/assets/Crackers/730331.png": {
    "src": "/assets/optimized/730331-02210e202bda-1280.webp",
    "srcSet": "/assets/optimized/730331-02210e202bda-160.webp 160w, /assets/optimized/730331-02210e202bda-320.webp 320w, /assets/optimized/730331-02210e202bda-640.webp 640w, /assets/optimized/730331-02210e202bda-1280.webp 1280w"
  },
  "/assets/Crackers/730332.png": {
    "src": "/assets/optimized/730332-6421b2483e11-1280.webp",
    "srcSet": "/assets/optimized/730332-6421b2483e11-160.webp 160w, /assets/optimized/730332-6421b2483e11-320.webp 320w, /assets/optimized/730332-6421b2483e11-640.webp 640w, /assets/optimized/730332-6421b2483e11-1280.webp 1280w"
  },
  "/assets/Crackers/730333.png": {
    "src": "/assets/optimized/730333-e2f784c10703-1280.webp",
    "srcSet": "/assets/optimized/730333-e2f784c10703-160.webp 160w, /assets/optimized/730333-e2f784c10703-320.webp 320w, /assets/optimized/730333-e2f784c10703-640.webp 640w, /assets/optimized/730333-e2f784c10703-1280.webp 1280w"
  },
  "/assets/Crackers/730560.png": {
    "src": "/assets/optimized/730560-e1b41dc0a9eb-852.webp",
    "srcSet": "/assets/optimized/730560-e1b41dc0a9eb-160.webp 160w, /assets/optimized/730560-e1b41dc0a9eb-320.webp 320w, /assets/optimized/730560-e1b41dc0a9eb-640.webp 640w, /assets/optimized/730560-e1b41dc0a9eb-852.webp 852w"
  },
  "/assets/Crackers/730561.png": {
    "src": "/assets/optimized/730561-9425459acb6c-902.webp",
    "srcSet": "/assets/optimized/730561-9425459acb6c-160.webp 160w, /assets/optimized/730561-9425459acb6c-320.webp 320w, /assets/optimized/730561-9425459acb6c-640.webp 640w, /assets/optimized/730561-9425459acb6c-902.webp 902w"
  },
  "/assets/Crackers/730562.png": {
    "src": "/assets/optimized/730562-42aaf013b799-857.webp",
    "srcSet": "/assets/optimized/730562-42aaf013b799-160.webp 160w, /assets/optimized/730562-42aaf013b799-320.webp 320w, /assets/optimized/730562-42aaf013b799-640.webp 640w, /assets/optimized/730562-42aaf013b799-857.webp 857w"
  },
  "/assets/Crackers/730565.png": {
    "src": "/assets/optimized/730565-0d5adefab0fb-1280.webp",
    "srcSet": "/assets/optimized/730565-0d5adefab0fb-160.webp 160w, /assets/optimized/730565-0d5adefab0fb-320.webp 320w, /assets/optimized/730565-0d5adefab0fb-640.webp 640w, /assets/optimized/730565-0d5adefab0fb-1280.webp 1280w"
  },
  "/assets/Crackers/730566.png": {
    "src": "/assets/optimized/730566-417dfe3b50a2-1280.webp",
    "srcSet": "/assets/optimized/730566-417dfe3b50a2-160.webp 160w, /assets/optimized/730566-417dfe3b50a2-320.webp 320w, /assets/optimized/730566-417dfe3b50a2-640.webp 640w, /assets/optimized/730566-417dfe3b50a2-1280.webp 1280w"
  },
  "/assets/Crackers/730570.png": {
    "src": "/assets/optimized/730570-8af6ca46c472-872.webp",
    "srcSet": "/assets/optimized/730570-8af6ca46c472-160.webp 160w, /assets/optimized/730570-8af6ca46c472-320.webp 320w, /assets/optimized/730570-8af6ca46c472-640.webp 640w, /assets/optimized/730570-8af6ca46c472-872.webp 872w"
  },
  "/assets/Crackers/730571.png": {
    "src": "/assets/optimized/730571-0ef01963b147-856.webp",
    "srcSet": "/assets/optimized/730571-0ef01963b147-160.webp 160w, /assets/optimized/730571-0ef01963b147-320.webp 320w, /assets/optimized/730571-0ef01963b147-640.webp 640w, /assets/optimized/730571-0ef01963b147-856.webp 856w"
  },
  "/assets/Crackers/730572.png": {
    "src": "/assets/optimized/730572-75738b52d23a-859.webp",
    "srcSet": "/assets/optimized/730572-75738b52d23a-160.webp 160w, /assets/optimized/730572-75738b52d23a-320.webp 320w, /assets/optimized/730572-75738b52d23a-640.webp 640w, /assets/optimized/730572-75738b52d23a-859.webp 859w"
  },
  "/assets/Flour/730306.png": {
    "src": "/assets/optimized/730306-99bb93a97a6f-373.webp",
    "srcSet": "/assets/optimized/730306-99bb93a97a6f-160.webp 160w, /assets/optimized/730306-99bb93a97a6f-320.webp 320w, /assets/optimized/730306-99bb93a97a6f-373.webp 373w"
  },
  "/assets/Flour/730307-Big.png": {
    "src": "/assets/optimized/730307-big-a39ab4c140bd-1280.webp",
    "srcSet": "/assets/optimized/730307-big-a39ab4c140bd-160.webp 160w, /assets/optimized/730307-big-a39ab4c140bd-320.webp 320w, /assets/optimized/730307-big-a39ab4c140bd-640.webp 640w, /assets/optimized/730307-big-a39ab4c140bd-1280.webp 1280w"
  },
  "/assets/Flour/730308-Big.png": {
    "src": "/assets/optimized/730308-big-fffa966bf330-1280.webp",
    "srcSet": "/assets/optimized/730308-big-fffa966bf330-160.webp 160w, /assets/optimized/730308-big-fffa966bf330-320.webp 320w, /assets/optimized/730308-big-fffa966bf330-640.webp 640w, /assets/optimized/730308-big-fffa966bf330-1280.webp 1280w"
  },
  "/assets/Flour/High gluten TUSCANINI_2,27Kg_2501013_facing.png": {
    "src": "/assets/optimized/high-gluten-tuscanini-2-27kg-2501013-facing-2e8fe4a748f0-1920.webp",
    "srcSet": "/assets/optimized/high-gluten-tuscanini-2-27kg-2501013-facing-2e8fe4a748f0-160.webp 160w, /assets/optimized/high-gluten-tuscanini-2-27kg-2501013-facing-2e8fe4a748f0-320.webp 320w, /assets/optimized/high-gluten-tuscanini-2-27kg-2501013-facing-2e8fe4a748f0-640.webp 640w, /assets/optimized/high-gluten-tuscanini-2-27kg-2501013-facing-2e8fe4a748f0-1280.webp 1280w, /assets/optimized/high-gluten-tuscanini-2-27kg-2501013-facing-2e8fe4a748f0-1920.webp 1920w"
  },
  "/assets/Foodservice/730009-focaccia-foodservice.webp": {
    "src": "/assets/optimized/730009-focaccia-foodservice-772988bcb91a-1280.webp",
    "srcSet": "/assets/optimized/730009-focaccia-foodservice-772988bcb91a-160.webp 160w, /assets/optimized/730009-focaccia-foodservice-772988bcb91a-320.webp 320w, /assets/optimized/730009-focaccia-foodservice-772988bcb91a-640.webp 640w, /assets/optimized/730009-focaccia-foodservice-772988bcb91a-1280.webp 1280w"
  },
  "/assets/Foodservice/730142-eggplant-cutlets.webp": {
    "src": "/assets/optimized/730142-eggplant-cutlets-beddb2299b78-1600.webp",
    "srcSet": "/assets/optimized/730142-eggplant-cutlets-beddb2299b78-160.webp 160w, /assets/optimized/730142-eggplant-cutlets-beddb2299b78-320.webp 320w, /assets/optimized/730142-eggplant-cutlets-beddb2299b78-640.webp 640w, /assets/optimized/730142-eggplant-cutlets-beddb2299b78-1280.webp 1280w, /assets/optimized/730142-eggplant-cutlets-beddb2299b78-1600.webp 1600w"
  },
  "/assets/Foodservice/730197-original-olive-pouch.webp": {
    "src": "/assets/optimized/730197-original-olive-pouch-d5f6393907fe-800.webp",
    "srcSet": "/assets/optimized/730197-original-olive-pouch-d5f6393907fe-160.webp 160w, /assets/optimized/730197-original-olive-pouch-d5f6393907fe-320.webp 320w, /assets/optimized/730197-original-olive-pouch-d5f6393907fe-640.webp 640w, /assets/optimized/730197-original-olive-pouch-d5f6393907fe-800.webp 800w"
  },
  "/assets/Foodservice/730251-caramel.webp": {
    "src": "/assets/optimized/730251-caramel-53bf9e8d9937-410.webp",
    "srcSet": "/assets/optimized/730251-caramel-53bf9e8d9937-160.webp 160w, /assets/optimized/730251-caramel-53bf9e8d9937-320.webp 320w, /assets/optimized/730251-caramel-53bf9e8d9937-410.webp 410w"
  },
  "/assets/Foodservice/730252-raspberry.webp": {
    "src": "/assets/optimized/730252-raspberry-f64d6a87974b-412.webp",
    "srcSet": "/assets/optimized/730252-raspberry-f64d6a87974b-160.webp 160w, /assets/optimized/730252-raspberry-f64d6a87974b-320.webp 320w, /assets/optimized/730252-raspberry-f64d6a87974b-412.webp 412w"
  },
  "/assets/Foodservice/730267-red-bulk.webp": {
    "src": "/assets/optimized/730267-red-bulk-7845fbd051ca-800.webp",
    "srcSet": "/assets/optimized/730267-red-bulk-7845fbd051ca-160.webp 160w, /assets/optimized/730267-red-bulk-7845fbd051ca-320.webp 320w, /assets/optimized/730267-red-bulk-7845fbd051ca-640.webp 640w, /assets/optimized/730267-red-bulk-7845fbd051ca-800.webp 800w"
  },
  "/assets/Foodservice/730349-potato-chips-shipper.webp": {
    "src": "/assets/optimized/730349-potato-chips-shipper-594b57f6c67a-556.webp",
    "srcSet": "/assets/optimized/730349-potato-chips-shipper-594b57f6c67a-160.webp 160w, /assets/optimized/730349-potato-chips-shipper-594b57f6c67a-320.webp 320w, /assets/optimized/730349-potato-chips-shipper-594b57f6c67a-556.webp 556w"
  },
  "/assets/Foodservice/730420-tuna-jar.webp": {
    "src": "/assets/optimized/730420-tuna-jar-49c38a933fdd-1280.webp",
    "srcSet": "/assets/optimized/730420-tuna-jar-49c38a933fdd-160.webp 160w, /assets/optimized/730420-tuna-jar-49c38a933fdd-320.webp 320w, /assets/optimized/730420-tuna-jar-49c38a933fdd-640.webp 640w, /assets/optimized/730420-tuna-jar-49c38a933fdd-1280.webp 1280w"
  },
  "/assets/Foodservice/730422-tuna-multipack.webp": {
    "src": "/assets/optimized/730422-tuna-multipack-f0a723733426-1280.webp",
    "srcSet": "/assets/optimized/730422-tuna-multipack-f0a723733426-160.webp 160w, /assets/optimized/730422-tuna-multipack-f0a723733426-320.webp 320w, /assets/optimized/730422-tuna-multipack-f0a723733426-640.webp 640w, /assets/optimized/730422-tuna-multipack-f0a723733426-1280.webp 1280w"
  },
  "/assets/Foodservice/730435-bulk-tuna-water.webp": {
    "src": "/assets/optimized/730435-bulk-tuna-water-2c3f6343f2b1-800.webp",
    "srcSet": "/assets/optimized/730435-bulk-tuna-water-2c3f6343f2b1-160.webp 160w, /assets/optimized/730435-bulk-tuna-water-2c3f6343f2b1-320.webp 320w, /assets/optimized/730435-bulk-tuna-water-2c3f6343f2b1-640.webp 640w, /assets/optimized/730435-bulk-tuna-water-2c3f6343f2b1-800.webp 800w"
  },
  "/assets/Foodservice/730436-bulk-tuna-oil.webp": {
    "src": "/assets/optimized/730436-bulk-tuna-oil-d9e2f3ffda70-800.webp",
    "srcSet": "/assets/optimized/730436-bulk-tuna-oil-d9e2f3ffda70-160.webp 160w, /assets/optimized/730436-bulk-tuna-oil-d9e2f3ffda70-320.webp 320w, /assets/optimized/730436-bulk-tuna-oil-d9e2f3ffda70-640.webp 640w, /assets/optimized/730436-bulk-tuna-oil-d9e2f3ffda70-800.webp 800w"
  },
  "/assets/Frozen/Mini Calzones/730128.png": {
    "src": "/assets/optimized/730128-8f5e5cc8e07e-500.webp",
    "srcSet": "/assets/optimized/730128-8f5e5cc8e07e-160.webp 160w, /assets/optimized/730128-8f5e5cc8e07e-320.webp 320w, /assets/optimized/730128-8f5e5cc8e07e-500.webp 500w"
  },
  "/assets/Frozen/Mini Calzones/730129.png": {
    "src": "/assets/optimized/730129-8aa960eaf8a2-500.webp",
    "srcSet": "/assets/optimized/730129-8aa960eaf8a2-160.webp 160w, /assets/optimized/730129-8aa960eaf8a2-320.webp 320w, /assets/optimized/730129-8aa960eaf8a2-500.webp 500w"
  },
  "/assets/Fruits/Capers/730375.png": {
    "src": "/assets/optimized/730375-cfaff748af71-652.webp",
    "srcSet": "/assets/optimized/730375-cfaff748af71-160.webp 160w, /assets/optimized/730375-cfaff748af71-320.webp 320w, /assets/optimized/730375-cfaff748af71-640.webp 640w, /assets/optimized/730375-cfaff748af71-652.webp 652w"
  },
  "/assets/Fruits/SundriedTomatoes/730439.png": {
    "src": "/assets/optimized/730439-509cda84cdf2-474.webp",
    "srcSet": "/assets/optimized/730439-509cda84cdf2-160.webp 160w, /assets/optimized/730439-509cda84cdf2-320.webp 320w, /assets/optimized/730439-509cda84cdf2-474.webp 474w"
  },
  "/assets/Gelato/730520-chocolate-gelato.png": {
    "src": "/assets/optimized/730520-chocolate-gelato-f13e8c53049b-1280.webp",
    "srcSet": "/assets/optimized/730520-chocolate-gelato-f13e8c53049b-160.webp 160w, /assets/optimized/730520-chocolate-gelato-f13e8c53049b-320.webp 320w, /assets/optimized/730520-chocolate-gelato-f13e8c53049b-640.webp 640w, /assets/optimized/730520-chocolate-gelato-f13e8c53049b-1280.webp 1280w"
  },
  "/assets/Gelato/730521-vanilla-gelato.png": {
    "src": "/assets/optimized/730521-vanilla-gelato-5d1d51cafc43-1280.webp",
    "srcSet": "/assets/optimized/730521-vanilla-gelato-5d1d51cafc43-160.webp 160w, /assets/optimized/730521-vanilla-gelato-5d1d51cafc43-320.webp 320w, /assets/optimized/730521-vanilla-gelato-5d1d51cafc43-640.webp 640w, /assets/optimized/730521-vanilla-gelato-5d1d51cafc43-1280.webp 1280w"
  },
  "/assets/Gelato/730522-hazelnut-gelato.png": {
    "src": "/assets/optimized/730522-hazelnut-gelato-754e3625aeba-1280.webp",
    "srcSet": "/assets/optimized/730522-hazelnut-gelato-754e3625aeba-160.webp 160w, /assets/optimized/730522-hazelnut-gelato-754e3625aeba-320.webp 320w, /assets/optimized/730522-hazelnut-gelato-754e3625aeba-640.webp 640w, /assets/optimized/730522-hazelnut-gelato-754e3625aeba-1280.webp 1280w"
  },
  "/assets/Gelato/730523-strawberry-banana-gelato.png": {
    "src": "/assets/optimized/730523-strawberry-banana-gelato-84527259d455-1280.webp",
    "srcSet": "/assets/optimized/730523-strawberry-banana-gelato-84527259d455-160.webp 160w, /assets/optimized/730523-strawberry-banana-gelato-84527259d455-320.webp 320w, /assets/optimized/730523-strawberry-banana-gelato-84527259d455-640.webp 640w, /assets/optimized/730523-strawberry-banana-gelato-84527259d455-1280.webp 1280w"
  },
  "/assets/Gelato/730530-chocolate-gelato-p.png": {
    "src": "/assets/optimized/730530-chocolate-gelato-p-55ff27b6e291-1280.webp",
    "srcSet": "/assets/optimized/730530-chocolate-gelato-p-55ff27b6e291-160.webp 160w, /assets/optimized/730530-chocolate-gelato-p-55ff27b6e291-320.webp 320w, /assets/optimized/730530-chocolate-gelato-p-55ff27b6e291-640.webp 640w, /assets/optimized/730530-chocolate-gelato-p-55ff27b6e291-1280.webp 1280w"
  },
  "/assets/Gelato/730531-vanilla-gelato-p.png": {
    "src": "/assets/optimized/730531-vanilla-gelato-p-d5a6e271e7a7-1280.webp",
    "srcSet": "/assets/optimized/730531-vanilla-gelato-p-d5a6e271e7a7-160.webp 160w, /assets/optimized/730531-vanilla-gelato-p-d5a6e271e7a7-320.webp 320w, /assets/optimized/730531-vanilla-gelato-p-d5a6e271e7a7-640.webp 640w, /assets/optimized/730531-vanilla-gelato-p-d5a6e271e7a7-1280.webp 1280w"
  },
  "/assets/Gelato/Sorbetto/730532-strawberry-sorbetto.png": {
    "src": "/assets/optimized/730532-strawberry-sorbetto-682a00fe98ff-1280.webp",
    "srcSet": "/assets/optimized/730532-strawberry-sorbetto-682a00fe98ff-160.webp 160w, /assets/optimized/730532-strawberry-sorbetto-682a00fe98ff-320.webp 320w, /assets/optimized/730532-strawberry-sorbetto-682a00fe98ff-640.webp 640w, /assets/optimized/730532-strawberry-sorbetto-682a00fe98ff-1280.webp 1280w"
  },
  "/assets/Gelato/Sorbetto/730533-lemon-sorbetto.png": {
    "src": "/assets/optimized/730533-lemon-sorbetto-f094854fd19c-1280.webp",
    "srcSet": "/assets/optimized/730533-lemon-sorbetto-f094854fd19c-160.webp 160w, /assets/optimized/730533-lemon-sorbetto-f094854fd19c-320.webp 320w, /assets/optimized/730533-lemon-sorbetto-f094854fd19c-640.webp 640w, /assets/optimized/730533-lemon-sorbetto-f094854fd19c-1280.webp 1280w"
  },
  "/assets/Gnocchi/Tuscanini-Mi-ni-Gnocchi-16oz-730312.png": {
    "src": "/assets/optimized/tuscanini-mi-ni-gnocchi-16oz-730312-f2e589703724-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-mi-ni-gnocchi-16oz-730312-f2e589703724-160.webp 160w, /assets/optimized/tuscanini-mi-ni-gnocchi-16oz-730312-f2e589703724-320.webp 320w, /assets/optimized/tuscanini-mi-ni-gnocchi-16oz-730312-f2e589703724-640.webp 640w, /assets/optimized/tuscanini-mi-ni-gnocchi-16oz-730312-f2e589703724-1280.webp 1280w"
  },
  "/assets/Jam/730242.png": {
    "src": "/assets/optimized/730242-aaff617a418b-800.webp",
    "srcSet": "/assets/optimized/730242-aaff617a418b-160.webp 160w, /assets/optimized/730242-aaff617a418b-320.webp 320w, /assets/optimized/730242-aaff617a418b-640.webp 640w, /assets/optimized/730242-aaff617a418b-800.webp 800w"
  },
  "/assets/Jam/730270.png": {
    "src": "/assets/optimized/730270-58b4411698bc-618.webp",
    "srcSet": "/assets/optimized/730270-58b4411698bc-160.webp 160w, /assets/optimized/730270-58b4411698bc-320.webp 320w, /assets/optimized/730270-58b4411698bc-618.webp 618w"
  },
  "/assets/Jam/730271-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730271-primary-shot-de546de6095f-1243.webp",
    "srcSet": "/assets/optimized/730271-primary-shot-de546de6095f-160.webp 160w, /assets/optimized/730271-primary-shot-de546de6095f-320.webp 320w, /assets/optimized/730271-primary-shot-de546de6095f-640.webp 640w, /assets/optimized/730271-primary-shot-de546de6095f-1243.webp 1243w"
  },
  "/assets/Jam/730273.png": {
    "src": "/assets/optimized/730273-41fed0a9e4fd-1280.webp",
    "srcSet": "/assets/optimized/730273-41fed0a9e4fd-160.webp 160w, /assets/optimized/730273-41fed0a9e4fd-320.webp 320w, /assets/optimized/730273-41fed0a9e4fd-640.webp 640w, /assets/optimized/730273-41fed0a9e4fd-1280.webp 1280w"
  },
  "/assets/Jam/730274.png": {
    "src": "/assets/optimized/730274-fc972de9e76c-1280.webp",
    "srcSet": "/assets/optimized/730274-fc972de9e76c-160.webp 160w, /assets/optimized/730274-fc972de9e76c-320.webp 320w, /assets/optimized/730274-fc972de9e76c-640.webp 640w, /assets/optimized/730274-fc972de9e76c-1280.webp 1280w"
  },
  "/assets/Jam/730275.png": {
    "src": "/assets/optimized/730275-a3f3b3fccbf6-1280.webp",
    "srcSet": "/assets/optimized/730275-a3f3b3fccbf6-160.webp 160w, /assets/optimized/730275-a3f3b3fccbf6-320.webp 320w, /assets/optimized/730275-a3f3b3fccbf6-640.webp 640w, /assets/optimized/730275-a3f3b3fccbf6-1280.webp 1280w"
  },
  "/assets/Jam/730276.png": {
    "src": "/assets/optimized/730276-9e9b307d03a0-591.webp",
    "srcSet": "/assets/optimized/730276-9e9b307d03a0-160.webp 160w, /assets/optimized/730276-9e9b307d03a0-320.webp 320w, /assets/optimized/730276-9e9b307d03a0-591.webp 591w"
  },
  "/assets/Lemon Juice/730285-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730285-primary-shot-6f87eafa733e-1280.webp",
    "srcSet": "/assets/optimized/730285-primary-shot-6f87eafa733e-160.webp 160w, /assets/optimized/730285-primary-shot-6f87eafa733e-320.webp 320w, /assets/optimized/730285-primary-shot-6f87eafa733e-640.webp 640w, /assets/optimized/730285-primary-shot-6f87eafa733e-1280.webp 1280w"
  },
  "/assets/Lemon Juice/730286.png": {
    "src": "/assets/optimized/730286-50860a3fb100-230.webp",
    "srcSet": "/assets/optimized/730286-50860a3fb100-160.webp 160w, /assets/optimized/730286-50860a3fb100-230.webp 230w"
  },
  "/assets/Olive Oil/730254.png": {
    "src": "/assets/optimized/730254-9a5d43c4965c-988.webp",
    "srcSet": "/assets/optimized/730254-9a5d43c4965c-160.webp 160w, /assets/optimized/730254-9a5d43c4965c-320.webp 320w, /assets/optimized/730254-9a5d43c4965c-640.webp 640w, /assets/optimized/730254-9a5d43c4965c-988.webp 988w"
  },
  "/assets/Olive Oil/730256-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730256-primary-shot-0b36978f0d3b-982.webp",
    "srcSet": "/assets/optimized/730256-primary-shot-0b36978f0d3b-160.webp 160w, /assets/optimized/730256-primary-shot-0b36978f0d3b-320.webp 320w, /assets/optimized/730256-primary-shot-0b36978f0d3b-640.webp 640w, /assets/optimized/730256-primary-shot-0b36978f0d3b-982.webp 982w"
  },
  "/assets/Olive Oil/730257.png": {
    "src": "/assets/optimized/730257-27d15d0adf17-985.webp",
    "srcSet": "/assets/optimized/730257-27d15d0adf17-160.webp 160w, /assets/optimized/730257-27d15d0adf17-320.webp 320w, /assets/optimized/730257-27d15d0adf17-640.webp 640w, /assets/optimized/730257-27d15d0adf17-985.webp 985w"
  },
  "/assets/Olive Oil/730406 Large.png": {
    "src": "/assets/optimized/730406-large-a25be0955319-390.webp",
    "srcSet": "/assets/optimized/730406-large-a25be0955319-160.webp 160w, /assets/optimized/730406-large-a25be0955319-320.webp 320w, /assets/optimized/730406-large-a25be0955319-390.webp 390w"
  },
  "/assets/Olive Oil/Tuscanini-Olive-Oil-Extra-Light-1L-730400.png": {
    "src": "/assets/optimized/tuscanini-olive-oil-extra-light-1l-730400-e1d8ce6c3fbe-637.webp",
    "srcSet": "/assets/optimized/tuscanini-olive-oil-extra-light-1l-730400-e1d8ce6c3fbe-160.webp 160w, /assets/optimized/tuscanini-olive-oil-extra-light-1l-730400-e1d8ce6c3fbe-320.webp 320w, /assets/optimized/tuscanini-olive-oil-extra-light-1l-730400-e1d8ce6c3fbe-637.webp 637w"
  },
  "/assets/Olive Oil/Tuscanini-Olive-Oil-Extra-Light-2L-730410.png": {
    "src": "/assets/optimized/tuscanini-olive-oil-extra-light-2l-730410-37262d3200f8-803.webp",
    "srcSet": "/assets/optimized/tuscanini-olive-oil-extra-light-2l-730410-37262d3200f8-160.webp 160w, /assets/optimized/tuscanini-olive-oil-extra-light-2l-730410-37262d3200f8-320.webp 320w, /assets/optimized/tuscanini-olive-oil-extra-light-2l-730410-37262d3200f8-640.webp 640w, /assets/optimized/tuscanini-olive-oil-extra-light-2l-730410-37262d3200f8-803.webp 803w"
  },
  "/assets/Olive Oil/Tuscanini-Olive-Oil-Extra-Light-3L-730415.png": {
    "src": "/assets/optimized/tuscanini-olive-oil-extra-light-3l-730415-a15ea624d337-1051.webp",
    "srcSet": "/assets/optimized/tuscanini-olive-oil-extra-light-3l-730415-a15ea624d337-160.webp 160w, /assets/optimized/tuscanini-olive-oil-extra-light-3l-730415-a15ea624d337-320.webp 320w, /assets/optimized/tuscanini-olive-oil-extra-light-3l-730415-a15ea624d337-640.webp 640w, /assets/optimized/tuscanini-olive-oil-extra-light-3l-730415-a15ea624d337-1051.webp 1051w"
  },
  "/assets/Olive/730183 - Pitted Olives w-Crushed Garlic.jpg": {
    "src": "/assets/optimized/730183-pitted-olives-w-crushed-garlic-c0bac02bd31a-1280.webp",
    "srcSet": "/assets/optimized/730183-pitted-olives-w-crushed-garlic-c0bac02bd31a-160.webp 160w, /assets/optimized/730183-pitted-olives-w-crushed-garlic-c0bac02bd31a-320.webp 320w, /assets/optimized/730183-pitted-olives-w-crushed-garlic-c0bac02bd31a-640.webp 640w, /assets/optimized/730183-pitted-olives-w-crushed-garlic-c0bac02bd31a-1280.webp 1280w"
  },
  "/assets/Olive/730184 -Cracked Marinated Olives.jpg": {
    "src": "/assets/optimized/730184-cracked-marinated-olives-0cee4ff30005-1280.webp",
    "srcSet": "/assets/optimized/730184-cracked-marinated-olives-0cee4ff30005-160.webp 160w, /assets/optimized/730184-cracked-marinated-olives-0cee4ff30005-320.webp 320w, /assets/optimized/730184-cracked-marinated-olives-0cee4ff30005-640.webp 640w, /assets/optimized/730184-cracked-marinated-olives-0cee4ff30005-1280.webp 1280w"
  },
  "/assets/Olive/730190.png": {
    "src": "/assets/optimized/730190-b4743253d4e1-774.webp",
    "srcSet": "/assets/optimized/730190-b4743253d4e1-160.webp 160w, /assets/optimized/730190-b4743253d4e1-320.webp 320w, /assets/optimized/730190-b4743253d4e1-640.webp 640w, /assets/optimized/730190-b4743253d4e1-774.webp 774w"
  },
  "/assets/Olive/730191-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730191-primary-shot-06bfe6dd222e-1187.webp",
    "srcSet": "/assets/optimized/730191-primary-shot-06bfe6dd222e-160.webp 160w, /assets/optimized/730191-primary-shot-06bfe6dd222e-320.webp 320w, /assets/optimized/730191-primary-shot-06bfe6dd222e-640.webp 640w, /assets/optimized/730191-primary-shot-06bfe6dd222e-1187.webp 1187w"
  },
  "/assets/Olive/730192.png": {
    "src": "/assets/optimized/730192-9ca7e25eb82d-477.webp",
    "srcSet": "/assets/optimized/730192-9ca7e25eb82d-160.webp 160w, /assets/optimized/730192-9ca7e25eb82d-320.webp 320w, /assets/optimized/730192-9ca7e25eb82d-477.webp 477w"
  },
  "/assets/Olive/Pouches/olive_garlic.jpg": {
    "src": "/assets/optimized/olive-garlic-2f412fe4a392-1280.webp",
    "srcSet": "/assets/optimized/olive-garlic-2f412fe4a392-160.webp 160w, /assets/optimized/olive-garlic-2f412fe4a392-320.webp 320w, /assets/optimized/olive-garlic-2f412fe4a392-640.webp 640w, /assets/optimized/olive-garlic-2f412fe4a392-1280.webp 1280w"
  },
  "/assets/Olive/Pouches/olive_origin.jpg": {
    "src": "/assets/optimized/olive-origin-95055e418227-1280.webp",
    "srcSet": "/assets/optimized/olive-origin-95055e418227-160.webp 160w, /assets/optimized/olive-origin-95055e418227-320.webp 320w, /assets/optimized/olive-origin-95055e418227-640.webp 640w, /assets/optimized/olive-origin-95055e418227-1280.webp 1280w"
  },
  "/assets/Olive/Pouches/olive_spicy.jpg": {
    "src": "/assets/optimized/olive-spicy-162fd5a30138-1280.webp",
    "srcSet": "/assets/optimized/olive-spicy-162fd5a30138-160.webp 160w, /assets/optimized/olive-spicy-162fd5a30138-320.webp 320w, /assets/optimized/olive-spicy-162fd5a30138-640.webp 640w, /assets/optimized/olive-spicy-162fd5a30138-1280.webp 1280w"
  },
  "/assets/Olive/Tuscanini-Bella-Italia-Mix-Pitted-Olives-730182.png": {
    "src": "/assets/optimized/tuscanini-bella-italia-mix-pitted-olives-730182-db5e1ffa4fa0-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-bella-italia-mix-pitted-olives-730182-db5e1ffa4fa0-160.webp 160w, /assets/optimized/tuscanini-bella-italia-mix-pitted-olives-730182-db5e1ffa4fa0-320.webp 320w, /assets/optimized/tuscanini-bella-italia-mix-pitted-olives-730182-db5e1ffa4fa0-640.webp 640w, /assets/optimized/tuscanini-bella-italia-mix-pitted-olives-730182-db5e1ffa4fa0-1280.webp 1280w"
  },
  "/assets/Olive/Tuscanini-Italian-Olive-Trio-Platter-730185.png": {
    "src": "/assets/optimized/tuscanini-italian-olive-trio-platter-730185-54e3b79320cf-1920.webp",
    "srcSet": "/assets/optimized/tuscanini-italian-olive-trio-platter-730185-54e3b79320cf-160.webp 160w, /assets/optimized/tuscanini-italian-olive-trio-platter-730185-54e3b79320cf-320.webp 320w, /assets/optimized/tuscanini-italian-olive-trio-platter-730185-54e3b79320cf-640.webp 640w, /assets/optimized/tuscanini-italian-olive-trio-platter-730185-54e3b79320cf-1280.webp 1280w, /assets/optimized/tuscanini-italian-olive-trio-platter-730185-54e3b79320cf-1920.webp 1920w"
  },
  "/assets/Olive/Tuscanini-Kalamata-Olives-730181.png": {
    "src": "/assets/optimized/tuscanini-kalamata-olives-730181-bbd458a780ee-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-kalamata-olives-730181-bbd458a780ee-160.webp 160w, /assets/optimized/tuscanini-kalamata-olives-730181-bbd458a780ee-320.webp 320w, /assets/optimized/tuscanini-kalamata-olives-730181-bbd458a780ee-640.webp 640w, /assets/optimized/tuscanini-kalamata-olives-730181-bbd458a780ee-1280.webp 1280w"
  },
  "/assets/Olive/Tuscanini-Spicy-Stuffed-Pimento-olives-8.5oz-730187.png": {
    "src": "/assets/optimized/tuscanini-spicy-stuffed-pimento-olives-8-5oz-730187-07beeaa7a784-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-spicy-stuffed-pimento-olives-8-5oz-730187-07beeaa7a784-160.webp 160w, /assets/optimized/tuscanini-spicy-stuffed-pimento-olives-8-5oz-730187-07beeaa7a784-320.webp 320w, /assets/optimized/tuscanini-spicy-stuffed-pimento-olives-8-5oz-730187-07beeaa7a784-640.webp 640w, /assets/optimized/tuscanini-spicy-stuffed-pimento-olives-8-5oz-730187-07beeaa7a784-1280.webp 1280w"
  },
  "/assets/Olive/Tuscanini-Sweet-Sicilian-Castelvetrano-Olives-730180.png": {
    "src": "/assets/optimized/tuscanini-sweet-sicilian-castelvetrano-olives-730180-f2206c014b5b-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-sweet-sicilian-castelvetrano-olives-730180-f2206c014b5b-160.webp 160w, /assets/optimized/tuscanini-sweet-sicilian-castelvetrano-olives-730180-f2206c014b5b-320.webp 320w, /assets/optimized/tuscanini-sweet-sicilian-castelvetrano-olives-730180-f2206c014b5b-640.webp 640w, /assets/optimized/tuscanini-sweet-sicilian-castelvetrano-olives-730180-f2206c014b5b-1280.webp 1280w"
  },
  "/assets/Parmesan Cheese/730170.png": {
    "src": "/assets/optimized/730170-45e505da8d3b-1454.webp",
    "srcSet": "/assets/optimized/730170-45e505da8d3b-160.webp 160w, /assets/optimized/730170-45e505da8d3b-320.webp 320w, /assets/optimized/730170-45e505da8d3b-640.webp 640w, /assets/optimized/730170-45e505da8d3b-1280.webp 1280w, /assets/optimized/730170-45e505da8d3b-1454.webp 1454w"
  },
  "/assets/Parmesan Cheese/730171.png": {
    "src": "/assets/optimized/730171-d27487368f0c-495.webp",
    "srcSet": "/assets/optimized/730171-d27487368f0c-160.webp 160w, /assets/optimized/730171-d27487368f0c-320.webp 320w, /assets/optimized/730171-d27487368f0c-495.webp 495w"
  },
  "/assets/Pasta/730320.png": {
    "src": "/assets/optimized/730320-8fbfc822ff79-800.webp",
    "srcSet": "/assets/optimized/730320-8fbfc822ff79-160.webp 160w, /assets/optimized/730320-8fbfc822ff79-320.webp 320w, /assets/optimized/730320-8fbfc822ff79-640.webp 640w, /assets/optimized/730320-8fbfc822ff79-800.webp 800w"
  },
  "/assets/Pasta/730321.png": {
    "src": "/assets/optimized/730321-6dc31e10453a-800.webp",
    "srcSet": "/assets/optimized/730321-6dc31e10453a-160.webp 160w, /assets/optimized/730321-6dc31e10453a-320.webp 320w, /assets/optimized/730321-6dc31e10453a-640.webp 640w, /assets/optimized/730321-6dc31e10453a-800.webp 800w"
  },
  "/assets/Pasta/730322.png": {
    "src": "/assets/optimized/730322-23b0dd4df46f-650.webp",
    "srcSet": "/assets/optimized/730322-23b0dd4df46f-160.webp 160w, /assets/optimized/730322-23b0dd4df46f-320.webp 320w, /assets/optimized/730322-23b0dd4df46f-640.webp 640w, /assets/optimized/730322-23b0dd4df46f-650.webp 650w"
  },
  "/assets/Pasta/730323.png": {
    "src": "/assets/optimized/730323-4d6e3e6cdf5f-523.webp",
    "srcSet": "/assets/optimized/730323-4d6e3e6cdf5f-160.webp 160w, /assets/optimized/730323-4d6e3e6cdf5f-320.webp 320w, /assets/optimized/730323-4d6e3e6cdf5f-523.webp 523w"
  },
  "/assets/Pasta/730324.png": {
    "src": "/assets/optimized/730324-a2a9f1d6faa3-596.webp",
    "srcSet": "/assets/optimized/730324-a2a9f1d6faa3-160.webp 160w, /assets/optimized/730324-a2a9f1d6faa3-320.webp 320w, /assets/optimized/730324-a2a9f1d6faa3-596.webp 596w"
  },
  "/assets/Pasta/730325.png": {
    "src": "/assets/optimized/730325-ba8d7831b75e-520.webp",
    "srcSet": "/assets/optimized/730325-ba8d7831b75e-160.webp 160w, /assets/optimized/730325-ba8d7831b75e-320.webp 320w, /assets/optimized/730325-ba8d7831b75e-520.webp 520w"
  },
  "/assets/Pasta/730326.png": {
    "src": "/assets/optimized/730326-b8a0fadc5a24-418.webp",
    "srcSet": "/assets/optimized/730326-b8a0fadc5a24-160.webp 160w, /assets/optimized/730326-b8a0fadc5a24-320.webp 320w, /assets/optimized/730326-b8a0fadc5a24-418.webp 418w"
  },
  "/assets/Pasta/Tuscanini Bronze Cut Fettuccine Comp copy.png": {
    "src": "/assets/optimized/tuscanini-bronze-cut-fettuccine-comp-copy-b853deba9fc8-750.webp",
    "srcSet": "/assets/optimized/tuscanini-bronze-cut-fettuccine-comp-copy-b853deba9fc8-160.webp 160w, /assets/optimized/tuscanini-bronze-cut-fettuccine-comp-copy-b853deba9fc8-320.webp 320w, /assets/optimized/tuscanini-bronze-cut-fettuccine-comp-copy-b853deba9fc8-640.webp 640w, /assets/optimized/tuscanini-bronze-cut-fettuccine-comp-copy-b853deba9fc8-750.webp 750w"
  },
  "/assets/Pasta/Tuscanini Bronze Cut Fusili Comp copy.png": {
    "src": "/assets/optimized/tuscanini-bronze-cut-fusili-comp-copy-884f4fae6282-1238.webp",
    "srcSet": "/assets/optimized/tuscanini-bronze-cut-fusili-comp-copy-884f4fae6282-160.webp 160w, /assets/optimized/tuscanini-bronze-cut-fusili-comp-copy-884f4fae6282-320.webp 320w, /assets/optimized/tuscanini-bronze-cut-fusili-comp-copy-884f4fae6282-640.webp 640w, /assets/optimized/tuscanini-bronze-cut-fusili-comp-copy-884f4fae6282-1238.webp 1238w"
  },
  "/assets/Pasta/Tuscanini Bronze Cut Penne Rigate Comp copy.png": {
    "src": "/assets/optimized/tuscanini-bronze-cut-penne-rigate-comp-copy-f0ba353efc6a-1238.webp",
    "srcSet": "/assets/optimized/tuscanini-bronze-cut-penne-rigate-comp-copy-f0ba353efc6a-160.webp 160w, /assets/optimized/tuscanini-bronze-cut-penne-rigate-comp-copy-f0ba353efc6a-320.webp 320w, /assets/optimized/tuscanini-bronze-cut-penne-rigate-comp-copy-f0ba353efc6a-640.webp 640w, /assets/optimized/tuscanini-bronze-cut-penne-rigate-comp-copy-f0ba353efc6a-1238.webp 1238w"
  },
  "/assets/Pasta/Tuscanini Bronze Cut Spaghetti Comp copy.png": {
    "src": "/assets/optimized/tuscanini-bronze-cut-spaghetti-comp-copy-de0f1778a4cc-750.webp",
    "srcSet": "/assets/optimized/tuscanini-bronze-cut-spaghetti-comp-copy-de0f1778a4cc-160.webp 160w, /assets/optimized/tuscanini-bronze-cut-spaghetti-comp-copy-de0f1778a4cc-320.webp 320w, /assets/optimized/tuscanini-bronze-cut-spaghetti-comp-copy-de0f1778a4cc-640.webp 640w, /assets/optimized/tuscanini-bronze-cut-spaghetti-comp-copy-de0f1778a4cc-750.webp 750w"
  },
  "/assets/Pasta/Tuscanini Cauliflower Gnocci Mockup.png": {
    "src": "/assets/optimized/tuscanini-cauliflower-gnocci-mockup-2712ec6548c4-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-cauliflower-gnocci-mockup-2712ec6548c4-160.webp 160w, /assets/optimized/tuscanini-cauliflower-gnocci-mockup-2712ec6548c4-320.webp 320w, /assets/optimized/tuscanini-cauliflower-gnocci-mockup-2712ec6548c4-640.webp 640w, /assets/optimized/tuscanini-cauliflower-gnocci-mockup-2712ec6548c4-1280.webp 1280w"
  },
  "/assets/Pasta/Tuscanini Classic Gnocci Mockup.png": {
    "src": "/assets/optimized/tuscanini-classic-gnocci-mockup-bcd1eba0e88b-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-classic-gnocci-mockup-bcd1eba0e88b-160.webp 160w, /assets/optimized/tuscanini-classic-gnocci-mockup-bcd1eba0e88b-320.webp 320w, /assets/optimized/tuscanini-classic-gnocci-mockup-bcd1eba0e88b-640.webp 640w, /assets/optimized/tuscanini-classic-gnocci-mockup-bcd1eba0e88b-1280.webp 1280w"
  },
  "/assets/Pasta/Tuscanini Gluten Free Gnocci Mockup.png": {
    "src": "/assets/optimized/tuscanini-gluten-free-gnocci-mockup-7dd4098beb06-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-gluten-free-gnocci-mockup-7dd4098beb06-160.webp 160w, /assets/optimized/tuscanini-gluten-free-gnocci-mockup-7dd4098beb06-320.webp 320w, /assets/optimized/tuscanini-gluten-free-gnocci-mockup-7dd4098beb06-640.webp 640w, /assets/optimized/tuscanini-gluten-free-gnocci-mockup-7dd4098beb06-1280.webp 1280w"
  },
  "/assets/Peppers/730438.png": {
    "src": "/assets/optimized/730438-87193c68efc2-469.webp",
    "srcSet": "/assets/optimized/730438-87193c68efc2-160.webp 160w, /assets/optimized/730438-87193c68efc2-320.webp 320w, /assets/optimized/730438-87193c68efc2-469.webp 469w"
  },
  "/assets/Peppers/730443.png": {
    "src": "/assets/optimized/730443-61946d9e7ef5-1192.webp",
    "srcSet": "/assets/optimized/730443-61946d9e7ef5-160.webp 160w, /assets/optimized/730443-61946d9e7ef5-320.webp 320w, /assets/optimized/730443-61946d9e7ef5-640.webp 640w, /assets/optimized/730443-61946d9e7ef5-1192.webp 1192w"
  },
  "/assets/Pesto/730230.png": {
    "src": "/assets/optimized/730230-daef1f426d27-335.webp",
    "srcSet": "/assets/optimized/730230-daef1f426d27-160.webp 160w, /assets/optimized/730230-daef1f426d27-320.webp 320w, /assets/optimized/730230-daef1f426d27-335.webp 335w"
  },
  "/assets/Pesto/730231.png": {
    "src": "/assets/optimized/730231-b65a57c609fa-335.webp",
    "srcSet": "/assets/optimized/730231-b65a57c609fa-160.webp 160w, /assets/optimized/730231-b65a57c609fa-320.webp 320w, /assets/optimized/730231-b65a57c609fa-335.webp 335w"
  },
  "/assets/Photos/PHOTO-2020-11-27-15-44-52.jpg": {
    "src": "/assets/optimized/photo-2020-11-27-15-44-52-e256904edba5-1004.webp",
    "srcSet": "/assets/optimized/photo-2020-11-27-15-44-52-e256904edba5-160.webp 160w, /assets/optimized/photo-2020-11-27-15-44-52-e256904edba5-320.webp 320w, /assets/optimized/photo-2020-11-27-15-44-52-e256904edba5-640.webp 640w, /assets/optimized/photo-2020-11-27-15-44-52-e256904edba5-1004.webp 1004w"
  },
  "/assets/Photos/PHOTO-2020-11-28-22-05-50.jpg": {
    "src": "/assets/optimized/photo-2020-11-28-22-05-50-f96ebd9f6895-1280.webp",
    "srcSet": "/assets/optimized/photo-2020-11-28-22-05-50-f96ebd9f6895-160.webp 160w, /assets/optimized/photo-2020-11-28-22-05-50-f96ebd9f6895-320.webp 320w, /assets/optimized/photo-2020-11-28-22-05-50-f96ebd9f6895-640.webp 640w, /assets/optimized/photo-2020-11-28-22-05-50-f96ebd9f6895-1280.webp 1280w"
  },
  "/assets/Photos/PHOTO-2020-11-28-22-13-28.jpg": {
    "src": "/assets/optimized/photo-2020-11-28-22-13-28-7a4f348e7207-1280.webp",
    "srcSet": "/assets/optimized/photo-2020-11-28-22-13-28-7a4f348e7207-160.webp 160w, /assets/optimized/photo-2020-11-28-22-13-28-7a4f348e7207-320.webp 320w, /assets/optimized/photo-2020-11-28-22-13-28-7a4f348e7207-640.webp 640w, /assets/optimized/photo-2020-11-28-22-13-28-7a4f348e7207-1280.webp 1280w"
  },
  "/assets/Photos/PHOTO-2020-11-28-22-23-56.jpg": {
    "src": "/assets/optimized/photo-2020-11-28-22-23-56-9c041ae01f4c-1280.webp",
    "srcSet": "/assets/optimized/photo-2020-11-28-22-23-56-9c041ae01f4c-160.webp 160w, /assets/optimized/photo-2020-11-28-22-23-56-9c041ae01f4c-320.webp 320w, /assets/optimized/photo-2020-11-28-22-23-56-9c041ae01f4c-640.webp 640w, /assets/optimized/photo-2020-11-28-22-23-56-9c041ae01f4c-1280.webp 1280w"
  },
  "/assets/Photos/PHOTO-2020-11-28-22-30-56.jpg": {
    "src": "/assets/optimized/photo-2020-11-28-22-30-56-0ddf2ee8154e-1280.webp",
    "srcSet": "/assets/optimized/photo-2020-11-28-22-30-56-0ddf2ee8154e-160.webp 160w, /assets/optimized/photo-2020-11-28-22-30-56-0ddf2ee8154e-320.webp 320w, /assets/optimized/photo-2020-11-28-22-30-56-0ddf2ee8154e-640.webp 640w, /assets/optimized/photo-2020-11-28-22-30-56-0ddf2ee8154e-1280.webp 1280w"
  },
  "/assets/Photos/backgrounds/italian-coast-hero.webp": {
    "src": "/assets/optimized/italian-coast-hero-0f5fdb2f1af7-512.webp",
    "srcSet": "/assets/optimized/italian-coast-hero-0f5fdb2f1af7-160.webp 160w, /assets/optimized/italian-coast-hero-0f5fdb2f1af7-320.webp 320w, /assets/optimized/italian-coast-hero-0f5fdb2f1af7-512.webp 512w"
  },
  "/assets/Photos/backgrounds/italian-coast.jpg": {
    "src": "/assets/optimized/italian-coast-cef146b76214-512.webp",
    "srcSet": "/assets/optimized/italian-coast-cef146b76214-160.webp 160w, /assets/optimized/italian-coast-cef146b76214-320.webp 320w, /assets/optimized/italian-coast-cef146b76214-512.webp 512w"
  },
  "/assets/Photos/backgrounds/italian-village-hero.webp": {
    "src": "/assets/optimized/italian-village-hero-25379e76442d-512.webp",
    "srcSet": "/assets/optimized/italian-village-hero-25379e76442d-160.webp 160w, /assets/optimized/italian-village-hero-25379e76442d-320.webp 320w, /assets/optimized/italian-village-hero-25379e76442d-512.webp 512w"
  },
  "/assets/Pizza/730100.png": {
    "src": "/assets/optimized/730100-3d83edc33d75-800.webp",
    "srcSet": "/assets/optimized/730100-3d83edc33d75-160.webp 160w, /assets/optimized/730100-3d83edc33d75-320.webp 320w, /assets/optimized/730100-3d83edc33d75-640.webp 640w, /assets/optimized/730100-3d83edc33d75-800.webp 800w"
  },
  "/assets/Pizza/730101.png": {
    "src": "/assets/optimized/730101-75a8bc4a26e4-800.webp",
    "srcSet": "/assets/optimized/730101-75a8bc4a26e4-160.webp 160w, /assets/optimized/730101-75a8bc4a26e4-320.webp 320w, /assets/optimized/730101-75a8bc4a26e4-640.webp 640w, /assets/optimized/730101-75a8bc4a26e4-800.webp 800w"
  },
  "/assets/Pizza/730102.png": {
    "src": "/assets/optimized/730102-2a3d0a58d3fb-800.webp",
    "srcSet": "/assets/optimized/730102-2a3d0a58d3fb-160.webp 160w, /assets/optimized/730102-2a3d0a58d3fb-320.webp 320w, /assets/optimized/730102-2a3d0a58d3fb-640.webp 640w, /assets/optimized/730102-2a3d0a58d3fb-800.webp 800w"
  },
  "/assets/Pizza/730103.png": {
    "src": "/assets/optimized/730103-f3a393a6bea0-800.webp",
    "srcSet": "/assets/optimized/730103-f3a393a6bea0-160.webp 160w, /assets/optimized/730103-f3a393a6bea0-320.webp 320w, /assets/optimized/730103-f3a393a6bea0-640.webp 640w, /assets/optimized/730103-f3a393a6bea0-800.webp 800w"
  },
  "/assets/Pizza/730115.png": {
    "src": "/assets/optimized/730115-c6d5f8f4477d-800.webp",
    "srcSet": "/assets/optimized/730115-c6d5f8f4477d-160.webp 160w, /assets/optimized/730115-c6d5f8f4477d-320.webp 320w, /assets/optimized/730115-c6d5f8f4477d-640.webp 640w, /assets/optimized/730115-c6d5f8f4477d-800.webp 800w"
  },
  "/assets/Pizza/730126.png": {
    "src": "/assets/optimized/730126-cbed296f4921-752.webp",
    "srcSet": "/assets/optimized/730126-cbed296f4921-160.webp 160w, /assets/optimized/730126-cbed296f4921-320.webp 320w, /assets/optimized/730126-cbed296f4921-640.webp 640w, /assets/optimized/730126-cbed296f4921-752.webp 752w"
  },
  "/assets/Pizza/730127.png": {
    "src": "/assets/optimized/730127-afda6a933027-756.webp",
    "srcSet": "/assets/optimized/730127-afda6a933027-160.webp 160w, /assets/optimized/730127-afda6a933027-320.webp 320w, /assets/optimized/730127-afda6a933027-640.webp 640w, /assets/optimized/730127-afda6a933027-756.webp 756w"
  },
  "/assets/Pizza/730500.png": {
    "src": "/assets/optimized/730500-93b2aa44ed4d-800.webp",
    "srcSet": "/assets/optimized/730500-93b2aa44ed4d-160.webp 160w, /assets/optimized/730500-93b2aa44ed4d-320.webp 320w, /assets/optimized/730500-93b2aa44ed4d-640.webp 640w, /assets/optimized/730500-93b2aa44ed4d-800.webp 800w"
  },
  "/assets/Pizza/730501.png": {
    "src": "/assets/optimized/730501-15340131d69a-800.webp",
    "srcSet": "/assets/optimized/730501-15340131d69a-160.webp 160w, /assets/optimized/730501-15340131d69a-320.webp 320w, /assets/optimized/730501-15340131d69a-640.webp 640w, /assets/optimized/730501-15340131d69a-800.webp 800w"
  },
  "/assets/Pizza/Tuscanini-Bianca-White-Pizza.png": {
    "src": "/assets/optimized/tuscanini-bianca-white-pizza-fd691b3b2e78-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-bianca-white-pizza-fd691b3b2e78-160.webp 160w, /assets/optimized/tuscanini-bianca-white-pizza-fd691b3b2e78-320.webp 320w, /assets/optimized/tuscanini-bianca-white-pizza-fd691b3b2e78-640.webp 640w, /assets/optimized/tuscanini-bianca-white-pizza-fd691b3b2e78-1280.webp 1280w"
  },
  "/assets/Pizza/Tuscanini-Creamy-ricotta.png": {
    "src": "/assets/optimized/tuscanini-creamy-ricotta-3a98ca198527-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-creamy-ricotta-3a98ca198527-160.webp 160w, /assets/optimized/tuscanini-creamy-ricotta-3a98ca198527-320.webp 320w, /assets/optimized/tuscanini-creamy-ricotta-3a98ca198527-640.webp 640w, /assets/optimized/tuscanini-creamy-ricotta-3a98ca198527-1280.webp 1280w"
  },
  "/assets/Salt/730280.png": {
    "src": "/assets/optimized/730280-f1dca9ffc2ae-990.webp",
    "srcSet": "/assets/optimized/730280-f1dca9ffc2ae-160.webp 160w, /assets/optimized/730280-f1dca9ffc2ae-320.webp 320w, /assets/optimized/730280-f1dca9ffc2ae-640.webp 640w, /assets/optimized/730280-f1dca9ffc2ae-990.webp 990w"
  },
  "/assets/Salt/730281.png": {
    "src": "/assets/optimized/730281-3895898a37f2-986.webp",
    "srcSet": "/assets/optimized/730281-3895898a37f2-160.webp 160w, /assets/optimized/730281-3895898a37f2-320.webp 320w, /assets/optimized/730281-3895898a37f2-640.webp 640w, /assets/optimized/730281-3895898a37f2-986.webp 986w"
  },
  "/assets/Salt/730282.png": {
    "src": "/assets/optimized/730282-da5a9d8ef272-800.webp",
    "srcSet": "/assets/optimized/730282-da5a9d8ef272-160.webp 160w, /assets/optimized/730282-da5a9d8ef272-320.webp 320w, /assets/optimized/730282-da5a9d8ef272-640.webp 640w, /assets/optimized/730282-da5a9d8ef272-800.webp 800w"
  },
  "/assets/Salt/730283.png": {
    "src": "/assets/optimized/730283-b2c4147e6476-800.webp",
    "srcSet": "/assets/optimized/730283-b2c4147e6476-160.webp 160w, /assets/optimized/730283-b2c4147e6476-320.webp 320w, /assets/optimized/730283-b2c4147e6476-640.webp 640w, /assets/optimized/730283-b2c4147e6476-800.webp 800w"
  },
  "/assets/Salt/730284.png": {
    "src": "/assets/optimized/730284-09b5e76ddcd4-800.webp",
    "srcSet": "/assets/optimized/730284-09b5e76ddcd4-160.webp 160w, /assets/optimized/730284-09b5e76ddcd4-320.webp 320w, /assets/optimized/730284-09b5e76ddcd4-640.webp 640w, /assets/optimized/730284-09b5e76ddcd4-800.webp 800w"
  },
  "/assets/Sauces/730200.png": {
    "src": "/assets/optimized/730200-8ceb5f2905bb-954.webp",
    "srcSet": "/assets/optimized/730200-8ceb5f2905bb-160.webp 160w, /assets/optimized/730200-8ceb5f2905bb-320.webp 320w, /assets/optimized/730200-8ceb5f2905bb-640.webp 640w, /assets/optimized/730200-8ceb5f2905bb-954.webp 954w"
  },
  "/assets/Sauces/730205 Traditional Pizza Sauce.jpg": {
    "src": "/assets/optimized/730205-traditional-pizza-sauce-8d26c3dd3e83-1280.webp",
    "srcSet": "/assets/optimized/730205-traditional-pizza-sauce-8d26c3dd3e83-160.webp 160w, /assets/optimized/730205-traditional-pizza-sauce-8d26c3dd3e83-320.webp 320w, /assets/optimized/730205-traditional-pizza-sauce-8d26c3dd3e83-640.webp 640w, /assets/optimized/730205-traditional-pizza-sauce-8d26c3dd3e83-1280.webp 1280w"
  },
  "/assets/Sauces/730205.png": {
    "src": "/assets/optimized/730205-fbe73cb1a221-979.webp",
    "srcSet": "/assets/optimized/730205-fbe73cb1a221-160.webp 160w, /assets/optimized/730205-fbe73cb1a221-320.webp 320w, /assets/optimized/730205-fbe73cb1a221-640.webp 640w, /assets/optimized/730205-fbe73cb1a221-979.webp 979w"
  },
  "/assets/Sauces/730206 Napoletana Pasta Sauce.jpg": {
    "src": "/assets/optimized/730206-napoletana-pasta-sauce-a3ae38337d76-1280.webp",
    "srcSet": "/assets/optimized/730206-napoletana-pasta-sauce-a3ae38337d76-160.webp 160w, /assets/optimized/730206-napoletana-pasta-sauce-a3ae38337d76-320.webp 320w, /assets/optimized/730206-napoletana-pasta-sauce-a3ae38337d76-640.webp 640w, /assets/optimized/730206-napoletana-pasta-sauce-a3ae38337d76-1280.webp 1280w"
  },
  "/assets/Sauces/730206.png": {
    "src": "/assets/optimized/730206-3c3f57e90e0c-979.webp",
    "srcSet": "/assets/optimized/730206-3c3f57e90e0c-160.webp 160w, /assets/optimized/730206-3c3f57e90e0c-320.webp 320w, /assets/optimized/730206-3c3f57e90e0c-640.webp 640w, /assets/optimized/730206-3c3f57e90e0c-979.webp 979w"
  },
  "/assets/Sauces/730207 Classic Marinara Sauce.jpg": {
    "src": "/assets/optimized/730207-classic-marinara-sauce-01db5392bdbc-1280.webp",
    "srcSet": "/assets/optimized/730207-classic-marinara-sauce-01db5392bdbc-160.webp 160w, /assets/optimized/730207-classic-marinara-sauce-01db5392bdbc-320.webp 320w, /assets/optimized/730207-classic-marinara-sauce-01db5392bdbc-640.webp 640w, /assets/optimized/730207-classic-marinara-sauce-01db5392bdbc-1280.webp 1280w"
  },
  "/assets/Sauces/730207.png": {
    "src": "/assets/optimized/730207-ecdb11a6be0a-981.webp",
    "srcSet": "/assets/optimized/730207-ecdb11a6be0a-160.webp 160w, /assets/optimized/730207-ecdb11a6be0a-320.webp 320w, /assets/optimized/730207-ecdb11a6be0a-640.webp 640w, /assets/optimized/730207-ecdb11a6be0a-981.webp 981w"
  },
  "/assets/Sauces/730208 Zesty Marinara Sauce.jpg": {
    "src": "/assets/optimized/730208-zesty-marinara-sauce-dc32352944dd-1280.webp",
    "srcSet": "/assets/optimized/730208-zesty-marinara-sauce-dc32352944dd-160.webp 160w, /assets/optimized/730208-zesty-marinara-sauce-dc32352944dd-320.webp 320w, /assets/optimized/730208-zesty-marinara-sauce-dc32352944dd-640.webp 640w, /assets/optimized/730208-zesty-marinara-sauce-dc32352944dd-1280.webp 1280w"
  },
  "/assets/Sauces/730208.png": {
    "src": "/assets/optimized/730208-cd4bd1f7adad-979.webp",
    "srcSet": "/assets/optimized/730208-cd4bd1f7adad-160.webp 160w, /assets/optimized/730208-cd4bd1f7adad-320.webp 320w, /assets/optimized/730208-cd4bd1f7adad-640.webp 640w, /assets/optimized/730208-cd4bd1f7adad-979.webp 979w"
  },
  "/assets/Sauces/730220-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730220-primary-shot-31405fb26d5b-1280.webp",
    "srcSet": "/assets/optimized/730220-primary-shot-31405fb26d5b-160.webp 160w, /assets/optimized/730220-primary-shot-31405fb26d5b-320.webp 320w, /assets/optimized/730220-primary-shot-31405fb26d5b-640.webp 640w, /assets/optimized/730220-primary-shot-31405fb26d5b-1280.webp 1280w"
  },
  "/assets/Sauces/730221-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730221-primary-shot-c6dc90933e56-1280.webp",
    "srcSet": "/assets/optimized/730221-primary-shot-c6dc90933e56-160.webp 160w, /assets/optimized/730221-primary-shot-c6dc90933e56-320.webp 320w, /assets/optimized/730221-primary-shot-c6dc90933e56-640.webp 640w, /assets/optimized/730221-primary-shot-c6dc90933e56-1280.webp 1280w"
  },
  "/assets/Sauces/730222-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730222-primary-shot-259917c481ab-1280.webp",
    "srcSet": "/assets/optimized/730222-primary-shot-259917c481ab-160.webp 160w, /assets/optimized/730222-primary-shot-259917c481ab-320.webp 320w, /assets/optimized/730222-primary-shot-259917c481ab-640.webp 640w, /assets/optimized/730222-primary-shot-259917c481ab-1280.webp 1280w"
  },
  "/assets/Sauces/730223-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730223-primary-shot-98e7ebc814ce-1280.webp",
    "srcSet": "/assets/optimized/730223-primary-shot-98e7ebc814ce-160.webp 160w, /assets/optimized/730223-primary-shot-98e7ebc814ce-320.webp 320w, /assets/optimized/730223-primary-shot-98e7ebc814ce-640.webp 640w, /assets/optimized/730223-primary-shot-98e7ebc814ce-1280.webp 1280w"
  },
  "/assets/Sauces/730234-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730234-primary-shot-2d54612f0304-664.webp",
    "srcSet": "/assets/optimized/730234-primary-shot-2d54612f0304-160.webp 160w, /assets/optimized/730234-primary-shot-2d54612f0304-320.webp 320w, /assets/optimized/730234-primary-shot-2d54612f0304-640.webp 640w, /assets/optimized/730234-primary-shot-2d54612f0304-664.webp 664w"
  },
  "/assets/Sauces/Tomato-Juice-2.png": {
    "src": "/assets/optimized/tomato-juice-2-275cadd240cc-634.webp",
    "srcSet": "/assets/optimized/tomato-juice-2-275cadd240cc-160.webp 160w, /assets/optimized/tomato-juice-2-275cadd240cc-320.webp 320w, /assets/optimized/tomato-juice-2-275cadd240cc-634.webp 634w"
  },
  "/assets/Sauces/Tomato-Puree.png": {
    "src": "/assets/optimized/tomato-puree-2dc05c93a1f6-683.webp",
    "srcSet": "/assets/optimized/tomato-puree-2dc05c93a1f6-160.webp 160w, /assets/optimized/tomato-puree-2dc05c93a1f6-320.webp 320w, /assets/optimized/tomato-puree-2dc05c93a1f6-640.webp 640w, /assets/optimized/tomato-puree-2dc05c93a1f6-683.webp 683w"
  },
  "/assets/Sauces/Tuscanini Tomato Paste Tube_730211.png": {
    "src": "/assets/optimized/tuscanini-tomato-paste-tube-730211-3427a383eea6-621.webp",
    "srcSet": "/assets/optimized/tuscanini-tomato-paste-tube-730211-3427a383eea6-160.webp 160w, /assets/optimized/tuscanini-tomato-paste-tube-730211-3427a383eea6-320.webp 320w, /assets/optimized/tuscanini-tomato-paste-tube-730211-3427a383eea6-621.webp 621w"
  },
  "/assets/Sauces/Tuscanini Tomato Sauce Carton_730210.png": {
    "src": "/assets/optimized/tuscanini-tomato-sauce-carton-730210-aaa1a70b1a6f-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-tomato-sauce-carton-730210-aaa1a70b1a6f-160.webp 160w, /assets/optimized/tuscanini-tomato-sauce-carton-730210-aaa1a70b1a6f-320.webp 320w, /assets/optimized/tuscanini-tomato-sauce-carton-730210-aaa1a70b1a6f-640.webp 640w, /assets/optimized/tuscanini-tomato-sauce-carton-730210-aaa1a70b1a6f-1280.webp 1280w"
  },
  "/assets/Sauces/Tuscanini-Crushed-Tomatoes-730212.png": {
    "src": "/assets/optimized/tuscanini-crushed-tomatoes-730212-be37f586626c-632.webp",
    "srcSet": "/assets/optimized/tuscanini-crushed-tomatoes-730212-be37f586626c-160.webp 160w, /assets/optimized/tuscanini-crushed-tomatoes-730212-be37f586626c-320.webp 320w, /assets/optimized/tuscanini-crushed-tomatoes-730212-be37f586626c-632.webp 632w"
  },
  "/assets/Sauces/Tuscanini-Diced-Tomatoes-24.png": {
    "src": "/assets/optimized/tuscanini-diced-tomatoes-24-18bdd79d3447-628.webp",
    "srcSet": "/assets/optimized/tuscanini-diced-tomatoes-24-18bdd79d3447-160.webp 160w, /assets/optimized/tuscanini-diced-tomatoes-24-18bdd79d3447-320.webp 320w, /assets/optimized/tuscanini-diced-tomatoes-24-18bdd79d3447-628.webp 628w"
  },
  "/assets/Sauces/Tuscanini-Peeled-Tomatoes-28.png": {
    "src": "/assets/optimized/tuscanini-peeled-tomatoes-28-ddcf6e86704a-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-peeled-tomatoes-28-ddcf6e86704a-160.webp 160w, /assets/optimized/tuscanini-peeled-tomatoes-28-ddcf6e86704a-320.webp 320w, /assets/optimized/tuscanini-peeled-tomatoes-28-ddcf6e86704a-640.webp 640w, /assets/optimized/tuscanini-peeled-tomatoes-28-ddcf6e86704a-1280.webp 1280w"
  },
  "/assets/Sauces/Tuscanini-Tomato-Paste-Tube-730211.png": {
    "src": "/assets/optimized/tuscanini-tomato-paste-tube-730211-3427a383eea6-621.webp",
    "srcSet": "/assets/optimized/tuscanini-tomato-paste-tube-730211-3427a383eea6-160.webp 160w, /assets/optimized/tuscanini-tomato-paste-tube-730211-3427a383eea6-320.webp 320w, /assets/optimized/tuscanini-tomato-paste-tube-730211-3427a383eea6-621.webp 621w"
  },
  "/assets/Spice Grinder/730290.png": {
    "src": "/assets/optimized/730290-27f24bdf61e4-951.webp",
    "srcSet": "/assets/optimized/730290-27f24bdf61e4-160.webp 160w, /assets/optimized/730290-27f24bdf61e4-320.webp 320w, /assets/optimized/730290-27f24bdf61e4-640.webp 640w, /assets/optimized/730290-27f24bdf61e4-951.webp 951w"
  },
  "/assets/Spice Grinder/730291.png": {
    "src": "/assets/optimized/730291-20900272d298-931.webp",
    "srcSet": "/assets/optimized/730291-20900272d298-160.webp 160w, /assets/optimized/730291-20900272d298-320.webp 320w, /assets/optimized/730291-20900272d298-640.webp 640w, /assets/optimized/730291-20900272d298-931.webp 931w"
  },
  "/assets/Spice Grinder/730292.png": {
    "src": "/assets/optimized/730292-e2ad257e8a94-933.webp",
    "srcSet": "/assets/optimized/730292-e2ad257e8a94-160.webp 160w, /assets/optimized/730292-e2ad257e8a94-320.webp 320w, /assets/optimized/730292-e2ad257e8a94-640.webp 640w, /assets/optimized/730292-e2ad257e8a94-933.webp 933w"
  },
  "/assets/Spice Grinder/730293.png": {
    "src": "/assets/optimized/730293-b6fe381cce69-947.webp",
    "srcSet": "/assets/optimized/730293-b6fe381cce69-160.webp 160w, /assets/optimized/730293-b6fe381cce69-320.webp 320w, /assets/optimized/730293-b6fe381cce69-640.webp 640w, /assets/optimized/730293-b6fe381cce69-947.webp 947w"
  },
  "/assets/Spice Grinder/730294.png": {
    "src": "/assets/optimized/730294-8dcd8cb871d4-924.webp",
    "srcSet": "/assets/optimized/730294-8dcd8cb871d4-160.webp 160w, /assets/optimized/730294-8dcd8cb871d4-320.webp 320w, /assets/optimized/730294-8dcd8cb871d4-640.webp 640w, /assets/optimized/730294-8dcd8cb871d4-924.webp 924w"
  },
  "/assets/Spice Grinder/730295.png": {
    "src": "/assets/optimized/730295-d5f6126da8df-944.webp",
    "srcSet": "/assets/optimized/730295-d5f6126da8df-160.webp 160w, /assets/optimized/730295-d5f6126da8df-320.webp 320w, /assets/optimized/730295-d5f6126da8df-640.webp 640w, /assets/optimized/730295-d5f6126da8df-944.webp 944w"
  },
  "/assets/Truffle Ketchup/730233-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730233-primary-shot-af0ce23e1271-724.webp",
    "srcSet": "/assets/optimized/730233-primary-shot-af0ce23e1271-160.webp 160w, /assets/optimized/730233-primary-shot-af0ce23e1271-320.webp 320w, /assets/optimized/730233-primary-shot-af0ce23e1271-640.webp 640w, /assets/optimized/730233-primary-shot-af0ce23e1271-724.webp 724w"
  },
  "/assets/Truffles/730580.png": {
    "src": "/assets/optimized/730580-09759f0c8f47-1920.webp",
    "srcSet": "/assets/optimized/730580-09759f0c8f47-160.webp 160w, /assets/optimized/730580-09759f0c8f47-320.webp 320w, /assets/optimized/730580-09759f0c8f47-640.webp 640w, /assets/optimized/730580-09759f0c8f47-1280.webp 1280w, /assets/optimized/730580-09759f0c8f47-1920.webp 1920w"
  },
  "/assets/Truffles/730581.png": {
    "src": "/assets/optimized/730581-c5782b59d25d-1280.webp",
    "srcSet": "/assets/optimized/730581-c5782b59d25d-160.webp 160w, /assets/optimized/730581-c5782b59d25d-320.webp 320w, /assets/optimized/730581-c5782b59d25d-640.webp 640w, /assets/optimized/730581-c5782b59d25d-1280.webp 1280w"
  },
  "/assets/Truffles/730585.png": {
    "src": "/assets/optimized/730585-54632ab063a5-1280.webp",
    "srcSet": "/assets/optimized/730585-54632ab063a5-160.webp 160w, /assets/optimized/730585-54632ab063a5-320.webp 320w, /assets/optimized/730585-54632ab063a5-640.webp 640w, /assets/optimized/730585-54632ab063a5-1280.webp 1280w"
  },
  "/assets/Truffles/730586.webp": {
    "src": "/assets/optimized/730586-62221f71a221-1280.webp",
    "srcSet": "/assets/optimized/730586-62221f71a221-160.webp 160w, /assets/optimized/730586-62221f71a221-320.webp 320w, /assets/optimized/730586-62221f71a221-640.webp 640w, /assets/optimized/730586-62221f71a221-1280.webp 1280w"
  },
  "/assets/Truffles/730587.png": {
    "src": "/assets/optimized/730587-56730cf359a2-1280.webp",
    "srcSet": "/assets/optimized/730587-56730cf359a2-160.webp 160w, /assets/optimized/730587-56730cf359a2-320.webp 320w, /assets/optimized/730587-56730cf359a2-640.webp 640w, /assets/optimized/730587-56730cf359a2-1280.webp 1280w"
  },
  "/assets/Truffles/730588.png": {
    "src": "/assets/optimized/730588-f7aca9d15811-1280.webp",
    "srcSet": "/assets/optimized/730588-f7aca9d15811-160.webp 160w, /assets/optimized/730588-f7aca9d15811-320.webp 320w, /assets/optimized/730588-f7aca9d15811-640.webp 640w, /assets/optimized/730588-f7aca9d15811-1280.webp 1280w"
  },
  "/assets/Tuna/730420.png": {
    "src": "/assets/optimized/730420-871eb098a873-1280.webp",
    "srcSet": "/assets/optimized/730420-871eb098a873-160.webp 160w, /assets/optimized/730420-871eb098a873-320.webp 320w, /assets/optimized/730420-871eb098a873-640.webp 640w, /assets/optimized/730420-871eb098a873-1280.webp 1280w"
  },
  "/assets/Tuna/730425.png": {
    "src": "/assets/optimized/730425-cdd983d475f1-1280.webp",
    "srcSet": "/assets/optimized/730425-cdd983d475f1-160.webp 160w, /assets/optimized/730425-cdd983d475f1-320.webp 320w, /assets/optimized/730425-cdd983d475f1-640.webp 640w, /assets/optimized/730425-cdd983d475f1-1280.webp 1280w"
  },
  "/assets/Tuna/730426.png": {
    "src": "/assets/optimized/730426-e2488c14353b-1280.webp",
    "srcSet": "/assets/optimized/730426-e2488c14353b-160.webp 160w, /assets/optimized/730426-e2488c14353b-320.webp 320w, /assets/optimized/730426-e2488c14353b-640.webp 640w, /assets/optimized/730426-e2488c14353b-1280.webp 1280w"
  },
  "/assets/Tuna/730430.png": {
    "src": "/assets/optimized/730430-af82e9882405-1280.webp",
    "srcSet": "/assets/optimized/730430-af82e9882405-160.webp 160w, /assets/optimized/730430-af82e9882405-320.webp 320w, /assets/optimized/730430-af82e9882405-640.webp 640w, /assets/optimized/730430-af82e9882405-1280.webp 1280w"
  },
  "/assets/Tuna/730431.png": {
    "src": "/assets/optimized/730431-baed2ac7a450-1280.webp",
    "srcSet": "/assets/optimized/730431-baed2ac7a450-160.webp 160w, /assets/optimized/730431-baed2ac7a450-320.webp 320w, /assets/optimized/730431-baed2ac7a450-640.webp 640w, /assets/optimized/730431-baed2ac7a450-1280.webp 1280w"
  },
  "/assets/Tuna/730436.png": {
    "src": "/assets/optimized/730436-027e5183664c-800.webp",
    "srcSet": "/assets/optimized/730436-027e5183664c-160.webp 160w, /assets/optimized/730436-027e5183664c-320.webp 320w, /assets/optimized/730436-027e5183664c-640.webp 640w, /assets/optimized/730436-027e5183664c-800.webp 800w"
  },
  "/assets/Tuna/Tusc_Tuna_Fillet_Final.png": {
    "src": "/assets/optimized/tusc-tuna-fillet-final-de59973a1e5e-1280.webp",
    "srcSet": "/assets/optimized/tusc-tuna-fillet-final-de59973a1e5e-160.webp 160w, /assets/optimized/tusc-tuna-fillet-final-de59973a1e5e-320.webp 320w, /assets/optimized/tusc-tuna-fillet-final-de59973a1e5e-640.webp 640w, /assets/optimized/tusc-tuna-fillet-final-de59973a1e5e-1280.webp 1280w"
  },
  "/assets/Tuna/Tuscanini Tuna in Water.png": {
    "src": "/assets/optimized/tuscanini-tuna-in-water-014bc17bd9d7-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-tuna-in-water-014bc17bd9d7-160.webp 160w, /assets/optimized/tuscanini-tuna-in-water-014bc17bd9d7-320.webp 320w, /assets/optimized/tuscanini-tuna-in-water-014bc17bd9d7-640.webp 640w, /assets/optimized/tuscanini-tuna-in-water-014bc17bd9d7-1280.webp 1280w"
  },
  "/assets/Tuna/Tuscanini Ventresca Tuna.jpg": {
    "src": "/assets/optimized/tuscanini-ventresca-tuna-5b5235c93ba5-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-ventresca-tuna-5b5235c93ba5-160.webp 160w, /assets/optimized/tuscanini-ventresca-tuna-5b5235c93ba5-320.webp 320w, /assets/optimized/tuscanini-ventresca-tuna-5b5235c93ba5-640.webp 640w, /assets/optimized/tuscanini-ventresca-tuna-5b5235c93ba5-1280.webp 1280w"
  },
  "/assets/Tuna/Tuscanini Yellowfin Tuna in Olive Oil.jpg": {
    "src": "/assets/optimized/tuscanini-yellowfin-tuna-in-olive-oil-0ec544416879-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-yellowfin-tuna-in-olive-oil-0ec544416879-160.webp 160w, /assets/optimized/tuscanini-yellowfin-tuna-in-olive-oil-0ec544416879-320.webp 320w, /assets/optimized/tuscanini-yellowfin-tuna-in-olive-oil-0ec544416879-640.webp 640w, /assets/optimized/tuscanini-yellowfin-tuna-in-olive-oil-0ec544416879-1280.webp 1280w"
  },
  "/assets/Tuna/Tuscanini tuna in Olive Oil.png": {
    "src": "/assets/optimized/tuscanini-tuna-in-olive-oil-953b6531a107-1280.webp",
    "srcSet": "/assets/optimized/tuscanini-tuna-in-olive-oil-953b6531a107-160.webp 160w, /assets/optimized/tuscanini-tuna-in-olive-oil-953b6531a107-320.webp 320w, /assets/optimized/tuscanini-tuna-in-olive-oil-953b6531a107-640.webp 640w, /assets/optimized/tuscanini-tuna-in-olive-oil-953b6531a107-1280.webp 1280w"
  },
  "/assets/Vinegar/730247.png": {
    "src": "/assets/optimized/730247-d526dd6bd29b-217.webp",
    "srcSet": "/assets/optimized/730247-d526dd6bd29b-160.webp 160w, /assets/optimized/730247-d526dd6bd29b-217.webp 217w"
  },
  "/assets/Vinegar/730248.png": {
    "src": "/assets/optimized/730248-ded70225255c-800.webp",
    "srcSet": "/assets/optimized/730248-ded70225255c-160.webp 160w, /assets/optimized/730248-ded70225255c-320.webp 320w, /assets/optimized/730248-ded70225255c-640.webp 640w, /assets/optimized/730248-ded70225255c-800.webp 800w"
  },
  "/assets/Vinegar/730249.png": {
    "src": "/assets/optimized/730249-fa12ebec4431-800.webp",
    "srcSet": "/assets/optimized/730249-fa12ebec4431-160.webp 160w, /assets/optimized/730249-fa12ebec4431-320.webp 320w, /assets/optimized/730249-fa12ebec4431-640.webp 640w, /assets/optimized/730249-fa12ebec4431-800.webp 800w"
  },
  "/assets/Vinegar/730251.png": {
    "src": "/assets/optimized/730251-a04a99bc297b-206.webp",
    "srcSet": "/assets/optimized/730251-a04a99bc297b-160.webp 160w, /assets/optimized/730251-a04a99bc297b-206.webp 206w"
  },
  "/assets/Vinegar/730252.png": {
    "src": "/assets/optimized/730252-9c11ceebfb39-206.webp",
    "srcSet": "/assets/optimized/730252-9c11ceebfb39-160.webp 160w, /assets/optimized/730252-9c11ceebfb39-206.webp 206w"
  },
  "/assets/Vinegar/730260.png": {
    "src": "/assets/optimized/730260-40b5fb979a92-356.webp",
    "srcSet": "/assets/optimized/730260-40b5fb979a92-160.webp 160w, /assets/optimized/730260-40b5fb979a92-320.webp 320w, /assets/optimized/730260-40b5fb979a92-356.webp 356w"
  },
  "/assets/Vinegar/730261.png": {
    "src": "/assets/optimized/730261-4b18806fdf22-212.webp",
    "srcSet": "/assets/optimized/730261-4b18806fdf22-160.webp 160w, /assets/optimized/730261-4b18806fdf22-212.webp 212w"
  },
  "/assets/Vinegar/730265-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730265-primary-shot-589d12a76903-497.webp",
    "srcSet": "/assets/optimized/730265-primary-shot-589d12a76903-160.webp 160w, /assets/optimized/730265-primary-shot-589d12a76903-320.webp 320w, /assets/optimized/730265-primary-shot-589d12a76903-497.webp 497w"
  },
  "/assets/Vinegar/730266-PRIMARY-SHOT.png": {
    "src": "/assets/optimized/730266-primary-shot-8aca1275a1b9-491.webp",
    "srcSet": "/assets/optimized/730266-primary-shot-8aca1275a1b9-160.webp 160w, /assets/optimized/730266-primary-shot-8aca1275a1b9-320.webp 320w, /assets/optimized/730266-primary-shot-8aca1275a1b9-491.webp 491w"
  },
  "/assets/Vinegar/Tuscanini-Apple-Cider-Vinegar-with-Mother-730245.png": {
    "src": "/assets/optimized/tuscanini-apple-cider-vinegar-with-mother-730245-30f563410c99-430.webp",
    "srcSet": "/assets/optimized/tuscanini-apple-cider-vinegar-with-mother-730245-30f563410c99-160.webp 160w, /assets/optimized/tuscanini-apple-cider-vinegar-with-mother-730245-30f563410c99-320.webp 320w, /assets/optimized/tuscanini-apple-cider-vinegar-with-mother-730245-30f563410c99-430.webp 430w"
  },
  "/assets/Vinegar/Tuscanini-Balsamic-Vinegar-8.45-oz.png": {
    "src": "/assets/optimized/tuscanini-balsamic-vinegar-8-45-oz-e7c9c504984a-894.webp",
    "srcSet": "/assets/optimized/tuscanini-balsamic-vinegar-8-45-oz-e7c9c504984a-160.webp 160w, /assets/optimized/tuscanini-balsamic-vinegar-8-45-oz-e7c9c504984a-320.webp 320w, /assets/optimized/tuscanini-balsamic-vinegar-8-45-oz-e7c9c504984a-640.webp 640w, /assets/optimized/tuscanini-balsamic-vinegar-8-45-oz-e7c9c504984a-894.webp 894w"
  },
  "/assets/ads/balsamic-glaze.jpg": {
    "src": "/assets/optimized/balsamic-glaze-bca9c49c00e7-900.webp",
    "srcSet": "/assets/optimized/balsamic-glaze-bca9c49c00e7-160.webp 160w, /assets/optimized/balsamic-glaze-bca9c49c00e7-320.webp 320w, /assets/optimized/balsamic-glaze-bca9c49c00e7-640.webp 640w, /assets/optimized/balsamic-glaze-bca9c49c00e7-900.webp 900w"
  },
  "/assets/ads/balsamic-parallax.jpg": {
    "src": "/assets/optimized/balsamic-parallax-d50c77e8eda6-1780.webp",
    "srcSet": "/assets/optimized/balsamic-parallax-d50c77e8eda6-160.webp 160w, /assets/optimized/balsamic-parallax-d50c77e8eda6-320.webp 320w, /assets/optimized/balsamic-parallax-d50c77e8eda6-640.webp 640w, /assets/optimized/balsamic-parallax-d50c77e8eda6-1280.webp 1280w, /assets/optimized/balsamic-parallax-d50c77e8eda6-1780.webp 1780w"
  },
  "/assets/ads/beverages-wide.jpg": {
    "src": "/assets/optimized/beverages-wide-ebc0b5b40a12-1280.webp",
    "srcSet": "/assets/optimized/beverages-wide-ebc0b5b40a12-160.webp 160w, /assets/optimized/beverages-wide-ebc0b5b40a12-320.webp 320w, /assets/optimized/beverages-wide-ebc0b5b40a12-640.webp 640w, /assets/optimized/beverages-wide-ebc0b5b40a12-1280.webp 1280w"
  },
  "/assets/ads/gnocchi-recipe.jpg": {
    "src": "/assets/optimized/gnocchi-recipe-8a053737220f-1920.webp",
    "srcSet": "/assets/optimized/gnocchi-recipe-8a053737220f-160.webp 160w, /assets/optimized/gnocchi-recipe-8a053737220f-320.webp 320w, /assets/optimized/gnocchi-recipe-8a053737220f-640.webp 640w, /assets/optimized/gnocchi-recipe-8a053737220f-1280.webp 1280w, /assets/optimized/gnocchi-recipe-8a053737220f-1920.webp 1920w"
  },
  "/assets/ads/lemon-juice-parallax.jpg": {
    "src": "/assets/optimized/lemon-juice-parallax-1bf7fbfd3cf6-1280.webp",
    "srcSet": "/assets/optimized/lemon-juice-parallax-1bf7fbfd3cf6-160.webp 160w, /assets/optimized/lemon-juice-parallax-1bf7fbfd3cf6-320.webp 320w, /assets/optimized/lemon-juice-parallax-1bf7fbfd3cf6-640.webp 640w, /assets/optimized/lemon-juice-parallax-1bf7fbfd3cf6-1280.webp 1280w"
  },
  "/assets/ads/marinara-banner.jpg": {
    "src": "/assets/optimized/marinara-banner-625039d0e6a1-1780.webp",
    "srcSet": "/assets/optimized/marinara-banner-625039d0e6a1-160.webp 160w, /assets/optimized/marinara-banner-625039d0e6a1-320.webp 320w, /assets/optimized/marinara-banner-625039d0e6a1-640.webp 640w, /assets/optimized/marinara-banner-625039d0e6a1-1280.webp 1280w, /assets/optimized/marinara-banner-625039d0e6a1-1780.webp 1780w"
  },
  "/assets/ads/marinara-banner2.jpg": {
    "src": "/assets/optimized/marinara-banner2-f614f5e3999a-360.webp",
    "srcSet": "/assets/optimized/marinara-banner2-f614f5e3999a-160.webp 160w, /assets/optimized/marinara-banner2-f614f5e3999a-320.webp 320w, /assets/optimized/marinara-banner2-f614f5e3999a-360.webp 360w"
  },
  "/assets/ads/pizza-banner.jpg": {
    "src": "/assets/optimized/pizza-banner-ea3baf99065d-1545.webp",
    "srcSet": "/assets/optimized/pizza-banner-ea3baf99065d-160.webp 160w, /assets/optimized/pizza-banner-ea3baf99065d-320.webp 320w, /assets/optimized/pizza-banner-ea3baf99065d-640.webp 640w, /assets/optimized/pizza-banner-ea3baf99065d-1280.webp 1280w, /assets/optimized/pizza-banner-ea3baf99065d-1545.webp 1545w"
  },
  "/assets/ads/sparkling-parallax.jpg": {
    "src": "/assets/optimized/sparkling-parallax-d2cc5a3a490a-360.webp",
    "srcSet": "/assets/optimized/sparkling-parallax-d2cc5a3a490a-160.webp 160w, /assets/optimized/sparkling-parallax-d2cc5a3a490a-320.webp 320w, /assets/optimized/sparkling-parallax-d2cc5a3a490a-360.webp 360w"
  },
  "/assets/ads/sparkling-parallax2.jpg": {
    "src": "/assets/optimized/sparkling-parallax2-6f7697e50c8c-1780.webp",
    "srcSet": "/assets/optimized/sparkling-parallax2-6f7697e50c8c-160.webp 160w, /assets/optimized/sparkling-parallax2-6f7697e50c8c-320.webp 320w, /assets/optimized/sparkling-parallax2-6f7697e50c8c-640.webp 640w, /assets/optimized/sparkling-parallax2-6f7697e50c8c-1280.webp 1280w, /assets/optimized/sparkling-parallax2-6f7697e50c8c-1780.webp 1780w"
  },
  "/assets/ads/tomato-group-tuscanini-web.jpg": {
    "src": "/assets/optimized/tomato-group-tuscanini-web-fb110eaa34ed-1280.webp",
    "srcSet": "/assets/optimized/tomato-group-tuscanini-web-fb110eaa34ed-160.webp 160w, /assets/optimized/tomato-group-tuscanini-web-fb110eaa34ed-320.webp 320w, /assets/optimized/tomato-group-tuscanini-web-fb110eaa34ed-640.webp 640w, /assets/optimized/tomato-group-tuscanini-web-fb110eaa34ed-1280.webp 1280w"
  },
  "/assets/ads/tomatoes-parallax.jpg": {
    "src": "/assets/optimized/tomatoes-parallax-19483ab10aff-1280.webp",
    "srcSet": "/assets/optimized/tomatoes-parallax-19483ab10aff-160.webp 160w, /assets/optimized/tomatoes-parallax-19483ab10aff-320.webp 320w, /assets/optimized/tomatoes-parallax-19483ab10aff-640.webp 640w, /assets/optimized/tomatoes-parallax-19483ab10aff-1280.webp 1280w"
  },
  "/assets/ads/tuna-parallax.jpg": {
    "src": "/assets/optimized/tuna-parallax-c4947525c45c-360.webp",
    "srcSet": "/assets/optimized/tuna-parallax-c4947525c45c-160.webp 160w, /assets/optimized/tuna-parallax-c4947525c45c-320.webp 320w, /assets/optimized/tuna-parallax-c4947525c45c-360.webp 360w"
  },
  "/assets/ads/tuna-parallax2.jpg": {
    "src": "/assets/optimized/tuna-parallax2-b9cc44e67be3-360.webp",
    "srcSet": "/assets/optimized/tuna-parallax2-b9cc44e67be3-160.webp 160w, /assets/optimized/tuna-parallax2-b9cc44e67be3-320.webp 320w, /assets/optimized/tuna-parallax2-b9cc44e67be3-360.webp 360w"
  }
};
